### ISSUE TITLE
Kafka TLS encryption unavailable as a configurable option

### ISSUE THREAD

**Issue by ChannyClaus** [getsentry/snuba#1337]
https://github.com/getsentry/snuba/blob/4b9555cc1bcc66ce1066c7954583fbda46e2aafc/snuba/cli/bootstrap.py#L51-L58

When connecting to `Kafka` cluster via `confluent_kafka` client, it is not possible to use
a `kafka` cluster with TLS setup because the parameters used to construct the client are
hardcoded and not configurable from elsewhere (as shown in the snippet above).

Specifically, we would need `ssl.key.location`, `ssl.certificate.location`, and `security.protocol`
from `kakfa` config to be able to achieve this.

The right change to make here is probably to add an environment variable pointing to the path
where the `kafka` config is written to so that the configuration for `kafka` client can be
overriden with it.

**Comment by ChannyClaus** [comment]
not exactly sure if https://github.com/getsentry/sentry has the same problem, but if so it would
make sense to resolve this issue on both ends.

**Comment by fpacifici** [comment]
Hi,
thanks for reporting this. Unfortunately this is not supported at the moment.
There are more details about the rationale and what would take to support it in this other issue
#974 (comment)
