### ISSUE TITLE
[onprem] [20.11.1] "Could not construct valid time interval" errors in subscription consumer

### ISSUE THREAD

**Issue by caseyduquettesc** [getsentry/snuba#1527]
I upgraded to snuba 20.11.1 yesterday and one error I haven't been able to figure out yet is this constant error in `snuba-subscription-consumer-events` that produces invalid timestamp ranges.

```
2020-12-01 19:03:34,104 Flushing 29 items (from {Partition(topic=Topic(name='events'), index=5): Offsets(lo=268199555, hi=268199556), Partition(topic=Topic(name='events'), index=1): Offsets(lo=9283937, hi=9283938), Partition(topic=Topic(name='events'), index=7): Offsets(lo=173129991, hi=173130006), Partition(topic=Topic(name='events'), index=10): Offsets(lo=147809943, hi=147809956)})
snuba.utils.types.InvalidRangeError: (datetime.datetime(2020, 12, 1, 19, 3, 32, 220000), datetime.datetime(2020, 12, 1, 19, 3, 32, 195000))
    raise InvalidRangeError(self.lower, self.upper)
Traceback (most recent call last):
  File \"/usr/src/snuba/snuba/subscriptions/consumer.py\", line 129, in poll
    time_interval = Interval(previous_message.timestamp, message.timestamp)
  File \"<string>\", line 5, in __init__
  File \"/usr/src/snuba/snuba/utils/types.py\", line 67, in __post_init__
2020-12-01 19:03:33,833 Could not construct valid time interval between MessageDetails(offset=147809945, timestamp=datetime.datetime(2020, 12, 1, 19, 3, 32, 220000)) and Message(partition=Partition(topic=Topic(name='events'), index=10), offset=147809946)!
2020-12-01 19:03:31,990 Offset commit took 2ms
```

**snuba-subscription-consumer-events**
```
        - snuba
        - subscriptions
        - --auto-offset-reset=latest
        - --consumer-group=snuba-events-subscriptions-consumers
        - --topic=events
        - --result-topic=events-subscription-results
        - --dataset=events
        - --commit-log-topic=snuba-commit-log
        - --commit-log-group=snuba-consumers
        - --delay-seconds=60
        - --schedule-ttl=60
        - --log-level=DEBUG
        - --partitions=12
```

Any ideas?

**Comment by caseyduquettesc** [comment]
I managed to workaround the issue by reducing the precision of the previous message timestamps. It doesn't fix the issue, but reduces the occurrences enough that it happens maybe 10% of the time instead of 100%. The partitions that the exception does happen on will usually fix itself the next time it's processed since more time has passed.

```python
self.__previous_messages[message.partition] = MessageDetails(
    message.offset,
    # Reduce precision of timestamp to 1 digits of ms
    message.timestamp.replace(
        microsecond=int(message.timestamp.microsecond / 100000) * 100000
    ),
)
```

This solution works well enough for me that I won't take up anyone's time, I'll close this issue

**Comment by tkaemming** [comment]
This isn't as dangerous as it sounds — it is only a warning level log, not an error and is reasonably gracefully handled by the subscription consumer. It's caused by a topic misconfiguration as detailed here: https://github.com/getsentry/snuba/blob/805c795202eca51be23c19c632e902ebf5173d8c/snuba/subscriptions/consumer.py#L53-L57

We don't have a method to set up the topic with the correct configuration at this time (or audit and repair any incorrect topic configurations) but are looking to do that in the future.

Here are some more details about the consequences of this warning (besides lots of noise): getsentry/snuba#827

**Comment by caseyduquettesc** [comment]
Ah, excellent, I missed that part! That sounds like it will fix all my timestamp woes

**Comment by tkaemming** [comment]
It's very easy to miss (it's practically undocumented), so thanks for reminding us to take care of it.
