### ISSUE TITLE
[onprem] [20.11.1] Column "_tags_hash_map" causes exception 

### ISSUE THREAD

**Issue by caseyduquettesc** [getsentry/snuba#1528]
Upgraded to 20.11.1 recently and ran the migrations. One of them added a materialized column `_tags_hash_map`.

The `snuba consumer --storage events` process then goes into a crash loop because it tries to write to that column. I'm not sure why yet, it's tough to debug in production without stopping the event flow so I will try to debug tonight during non-peak hours, but thought I would mention the exception here.

```
# Exception after adding the column to the sentry_dist table
2020-12-01 19:34:32,536 Caught ClickhouseWriterError(code=44, message='Received from ch-shard0-production.default.svc.cluster.local:9000. DB::Exception: Cannot insert column _tags_hash_map, because it is MATERIALIZED column.. (version 20.3.21.2 (official build))', row=None), shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 161, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 109, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/processing/processor.py", line 144, in _run_once
    self.__processing_strategy.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/transform.py", line 55, in poll
    self.__next_step.poll()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 122, in poll
    self.__close_and_reset_batch()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 104, in __close_and_reset_batch
    self.__batch.close()
  File "/usr/src/snuba/snuba/utils/streams/processing/strategies/streaming/collect.py", line 64, in close
    self.__step.close()
  File "/usr/src/snuba/snuba/consumer.py", line 217, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumer.py", line 90, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 175, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 129, in join
    raise ClickhouseWriterError(code, message, row)
snuba.clickhouse.errors.ClickhouseWriterError: [44] Received from ch-shard0-production.default.svc.cluster.local:9000. DB::Exception: Cannot insert column _tags_hash_map, because it is MATERIALIZED column.. (version 20.3.21.2 (official build))
```

The workaround for now seems to be dropping the column from the `sentry_dist` table; leaving it in the _local table doesn't seem to be causing any problems. The only downside is that sometimes there are exceptions from the organization-stats api about the missing column, but it doesn't seem to be in the critical path.
```
# The non-critical error
DB::Exception: Missing columns: '_tags_hash_map' while processing query: 'SELECT toDateTime(intDiv(toUInt32(timestamp), 300) * 300, 'Universal') AS time, count() AS count FROM sentry_dist PREWHERE environment = 'production' WHERE (deleted = 0) AND (timestamp >= toDateTime('2020-11-30T10:37:01', 'Universal')) AND (timestamp < toDateTime('2020-12-01T10:37:01', 'Universal')) AND (project_id IN tuple(15)) AND has(_tags_hash_map, cityHash64('requestType=graphql')) 
```

**Comment by fpacifici** [comment]
Hi,

A couple of questions:
How did you end up having a sentry_dist table ? The migration system does not support a flow for distributed tables yet and as a consequence the onpremise repo is not able to deal with them. Specifically How didd you make the change to the distributed table DDL and would you be willing to share the schema of both distributed and local tables (use the `SHOW CREATE TABLE sentry_dist` clickhouse command).

Still the _tags_hash_map column should work as it is materialized. Could you check the value of these settings in your clickhouse node that hosts the distributed table? `input_format_null_as_default` `input_format_defaults_for_omitted_fields`. Trying to see if, for some reason, clickhouse is trying to force the default empty array in that materialized column on the distributed table.

Anyway, a way around is to restore the `_tags_hash_map` column but omit the materialized clause and leave it without default, that should do the trick. Though, as I mentioned, this is supposed to work in the original version even if the migration system does not supports it.

**Comment by caseyduquettesc** [comment]
> How did you end up having a sentry_dist table ? The migration system does not support a flow for distributed tables yet

Long story short, we set Snuba up before the migrations feature was added. Back then, it bootstrapped a `dev` table, I went back in and recreated it as a replicated table, and then after reading the clickhouse documentation, created a `sentry_dist` table and configured Snuba to use that. This was maybe 1.5 years ago and we had sort of a bastardized Sentry 9 with a bunch of half baked v10 features turned on. For the purposes of discussion, `sentry_local` is synonymous with `dev`, I'll try and update the name anywhere it appears in pasted output to reduce confusion.

> How didd you make the change to the distributed table DDL

Yes, I noticed I couldn't run the migrations against my cluster because single_node was False, which made sense. At first, I thought I could manually reconcile, but that was futile. I ended up applying a patch to simply print the SQL it would have executed for the migration if single_node is False. It would print the _local and _dist variants of the statements, which I would then go and run on all clickhouse instances.

> would you be willing to share the schema of both distributed and local tables

Sure, here is the output for both tables - https://gist.github.com/caseyduquettesc/0a026f549366728b9733ff60c0b956ec
Keep in mind the `sentry_dist` table still has the `_tags_hash_map` column missing. But I tried adding it with 
```
ALTER TABLE sentry_dist ADD COLUMN IF NOT EXISTS _tags_hash_map Array(UInt64) AFTER _tags_flattened;
```

> Could you check the value of these settings in your clickhouse node that hosts the distributed table? input_format_null_as_default input_format_defaults_for_omitted_fields

```
┌─name─────────────────────────────────────┬─value─┬─changed─┬─description──────────────────────────────────────────────────────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┐
│ input_format_defaults_for_omitted_fields │ 1     │       0 │ For input data calculate default expressions for omitted fields (it works for JSONEachRow, CSV and TSV formats). │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │
│ input_format_null_as_default             │ 0     │       0 │ For text input formats initialize null fields with default values if data type of this field is not nullable     │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │
└──────────────────────────────────────────┴───────┴─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┘
```

**Comment by caseyduquettesc** [comment]
I think I solved my own problem by simply recreating the _dist table. I am not seeing insert errors anymore. Should've listened to you, don't trust the migrations for dist tables :)

```sql
DROP TABLE sentry_dist;

CREATE TABLE default.sentry_dist AS default.sentry_local
ENGINE = Distributed(clicks_cluster, default, sentry_local, cityHash64(toString(event_id)));
```

**Comment by fpacifici** [comment]
Ok, it seems we should add a feature to export the DDL SQL from the migration system sooner than later. that would allow users with a distributed environment to  at least stay current with their distributed DDL.

When you recreated the table, did you add the materialized clause? If not, you could try adding it and setting `input_format_defaults_for_omitted_fields` to 0 (which is our default setting). I think that may be the cause as having it set to 1 may drive the consumer to try to insert an empty array in the materialized column. Clickhouse does not like when we try to write directly in a materialized column.

**Comment by caseyduquettesc** [comment]
> a feature to export the DDL SQL from the migration system

If supporting distributed+replicated configurations is not on the roadmap then I'd love to see a feature that can tell me what alterations I need to make. The assumption being that 1) most on-prem users likely will never need this support and 2) those who need it probably have the technical understanding to make the schema changes required as long as the changes are exposed.

> When you recreated the table, did you add the materialized clause?

I recreated it with exactly the command above, which I think copies the schema from the local table. When I look at the `CREATE TABLE` output, it does show that the column is now materialized. So the problem I guess is that a materialized local column must be materialized also in the distributed one, which makes sense.

I'll additionally try and set `input_format_defaults_for_omitted_fields` to 0, thanks for the helpful hint
