### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/snuba#1573]
Travis sprung some surprise billing changes on us awhile, so we are now prioritizing removing usage of TravisCI completely. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of.

**Comment by armenzg** [comment]
We're also moving away from Zeus to uploading code coverage information.
See [results](https://codecov.io/gh/getsentry/snuba/tree/e546a05ffa3da951172c98c801f530ba67a39963).

**Comment by armenzg** [comment]
@fpacifici Would you be able to update the required status checks?

**Comment by fpacifici** [comment]
Let's see if I remember how to do this ....
