### ISSUE TITLE
Create a unified Snuba consumer

### ISSUE THREAD

**Issue by BYK** [getsentry/snuba#1670]
Currently we have many Snuba consumers and seems like we are going to add more as we add more features around Snuba. This poses a maintenance and synchronization issue for on-premise as the growing number of consumers is hard to maintain. People also keep forgetting to add new consumers to the self-hosted repo, causing issues or missing features (this has happened twice now).

Proposal: introduce a `consumers` command to Snuba CLI that runs all core consumers with default settings (the settings we use in self-hosted) using multiprocessing so the consumers are still logically separate.

/cc @fpacifici @lynnagara @chadwhitacre

**Comment by BYK** [comment]
![84years](https://user-images.githubusercontent.com/126780/222106593-962ae69f-835d-4803-a483-5a01f5b616da.gif)

**Comment by chadwhitacre** [comment]
Here it is @JoshFerge. :)

**Comment by volokluev** [comment]
This is too much work that our team does not have time for at the moment.

**Comment by untitaker** [comment]
I think we should eventually do that but it's too early to create tickets. I think with lightweight deletes, EAP mutations, subscriptions the code became a lot more duplicated, the friction for creating new consumers in snuba feels very high, and the refactor in this issue would solve it. we did a similar project in sentry where we have way more consumers and it took me less than a quarter. I think it can be done in a limited fashion for rust only.
