### ISSUE TITLE
slow snuba healthcheck response

### ISSUE THREAD

**Issue by azhurbilo** [getsentry/snuba#1681]
### Environment

On-premise
Sentry 21.1.0

### Steps to Reproduce

After upgrade from 20.8 to 21.1 load to Clickhouse raised x2 times

Then I found that "sentry-snuba-api" pods from time to time restarted.
The reason

```
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  6m23s (x1534 over 18h)  kubelet  Readiness probe failed: Get http://XXX:1218/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2m19s (x1532 over 18h)  kubelet  Liveness probe failed: Get http://XXX:1218/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

-> 

```
XXX - - [16/Feb/2021:07:52:04 +0000] "POST /query HTTP/1.1" 200 420 "tsdb" "-"
XXX- - [16/Feb/2021:07:52:04 +0000] "POST /query HTTP/1.1" 200 582 "tsdb" "-"
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
stream closed
```

We use Sentry helm chart https://github.com/sentry-kubernetes/charts/blob/9.0.0/sentry/templates/deployment-snuba-api.yaml#L67-L86

and they set timeout = 2 sec

Almost all time response from `/` takes 200 ms

But I faced when sometimes it takes more than 2 sec

example

```
kubectl -n sentry exec -ti sentry-snuba-api-6ff68d6c77-24zlg -- bash

time curl http://localhost:1218/

<html/>
...
</html>
real	0m3.339s
user	0m0.008s
sys	0m0.000s
```

### Expected Result

Reduce count of killing container events

### Actual Result

Could you please explain do we need increase timeout from 2 seconds -> 5 seconds for example

Or may it's a problem on default uwsgi settings when uwsgi pool is queued and even query to "/" takes lot of time?

**Comment by BYK** [comment]
This is an issue you need to file over at https://github.com/sentry-kubernetes/charts, not here so closing 🙂
