### ISSUE TITLE
Syntax error in example query from docs

### ISSUE THREAD

**Issue by ChimeraCoder** [getsentry/snuba#1839]
### Environment

The sample query in the README.md has a syntax error (missing comma after the `to_date` field).

I'm happy to put together a pull request to fix it, but I'm not sure if it's autogenerated from somewhere else, since it's also used as the homepage for the web server itself.

I will note that, even adding the trailing comma, we stil 

### Steps to Reproduce

Current contents (in `HEAD` from `master`):

```json
{
    "project":[1,2],
    "selected_columns": ["tags[environment]"],
    "aggregations": [
        ["max", "received", "last_seen"]
    ],
    "conditions": [
        ["tags[environment]", "=", "prod"]
    ],
    "from_date": "2011-07-01T19:54:15",
    "to_date": "2018-07-06T19:54:15"
    "granularity": 3600,
    "groupby": ["group_id", "time"],
    "having": [],
    "issues": [],
}
```

which yields

```json
{
    "error": {
        "type": "json",
        "message": "Expecting ',' delimiter or '}': line 12 column 5 (char 291)"
    }
}
```

Note that adding the trailing comma yields a different syntax error; however, I'm not sure what the fix is here, because the property names all appear to be in single quotes. (Removing the trailing comma from the last entry doesn't fix it either - instead of a 400 we get an empty HTTP response.)

```json
{
    "error": {
        "type": "json",
        "message": "Expecting property name enclosed in double quotes: line 16 column 1 (char 386)"
    }
}
```

**Comment by nikhars** [comment]
The example query in the README has beed fixed.
