### ISSUE TITLE
Snuba still writes to table sentry_local instead of errors_local

### ISSUE THREAD

**Issue by artful88533** [getsentry/snuba#1969]
### Environment
Sentry self-hosted/on-premise 21.6.1

### Steps to Reproduce

1. Upgraded from 20.8.0 to 21.6.1
2. Migration created table `errors_local` and moved data there.
```
SELECT COUNT(*)
FROM errors_local

┌─COUNT()─┐
│ 7489513 │
└─────────┘
```
3. After all snuba process started (21.6.1) table `errors_local` doesn't increase but the table `sentry_local` started increasing
```
SELECT COUNT(*)
FROM sentry_local

┌─COUNT()─┐
│   16672 │
└─────────┘
```
4. In web dashboard I see only old data. Web is using new table `errors_local`

### Expected Result
As far as I understand the table `sentry_local` is deprecated.
Snuba has to work with table `errors_local`.

### Actual Result

Table `sentry_local` still using by snuba.

**Comment by artful88533** [comment]
How can I fix this problem?
Thank you!

**Comment by BYK** [comment]
Please update your local onpremise repo which changes some Snuba workers to accomodate this change.

**Comment by artful88533** [comment]
My mistake. I am using ansible and didn't change `storage` to `errors`.
Thank you!
