### ISSUE TITLE
snuba consumer left kafka cluster peacefully without exiting

### ISSUE THREAD

**Issue by leoskyrocker** [getsentry/snuba#1993]
### Environment

How do you use Sentry?
self-hosted (Sentry 10.1.0.dev0)

### Steps to Reproduce
Cannot reproduce easily. The service was operating until there was a timeout in polling which exceeded max.poll.interval.ms, and the snuba consumer decided to leave the consumer group.

### Expected Result
Since we run our Sentry on k8s, it would be handled properly if the snuba consumer exited when librdkafka decides to leave the consumer group.

### Actual Result
The snuba consumer stayed running even though it is no longer subscribing to the topic. As a result, no events were processed.

Logs:
```
%4|1624919321.320|MAXPOLL|rdkafka#consumer-2| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 481ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```

This was also the last log message of snuba consumer and it stayed there doing nothing afterwards.

**Comment by leoskyrocker** [comment]
it may or may not even be related to [this issue](https://github.com/getsentry/snuba/issues/1022)

**Comment by fpacifici** [comment]
Hi, 
 
max-poll.interval.ms is the maximum interval kafka waits without the consumer polling for new messages before considering the consumer dead (https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_max.poll.interval.ms). The snuba consumers are supposed to be polling continuously except when they are processing messages. 

I think we should understand why the consumer stopped polling as this situation is likely to be the consequence of another issue. 
- could you please provide logs from the snuba consumer for the 6 minutes before that last message you mentioned ? It would be important to understand if partitions were revoked or in general what was the consumer doing 
- do you have metrics about your k8s pod? Was it healthy during this period ?
- Sentry 10.1.0.dev0. Do you mean also snuba is in the version that came with sentry at that time or is it on a different version ? Did you upgrade snuba separately ?

Thanks
Filippo

**Comment by leoskyrocker** [comment]
I can provide some logs later, but what we saw was the last tick was trying to flush 2 messages, and that was probably the last poll as the timeout happened 5 minutes later.

Also prior than that (about 8 minutes before the failure) there were network errors manifested as CONNECTION RESET 104? but flushing continued afterwards so I wasn't sure that is necessarily related.

I can also open a separate issue to track the root cause if that's ideal for both of us.

I'm wondering if it's possible to keep this issue as a tracker of the underlying resolution in case the consumer leaves the group? So that we can discuss whether the community here is open to the idea of handling it or whether there's reason not to?

Anyways, really appreciate the help here and thank you so much for your time!

**Comment by leoskyrocker** [comment]
Regarding the snuba version, we were using the community's helm chart from sentry-kubernetes and was on its [version 2.1](https://github.com/sentry-kubernetes/charts/blob/951cf38c08a548e3db92d7848b6d1e6205d40b66/sentry/values.yaml#L16). 

This suggests that we were specifically pinned to this commit: 3fd2e7d6e8825c0b09f47b4d427d532b6c24ca08

**Comment by fpacifici** [comment]
> I'm wondering if it's possible to keep this issue as a tracker of the underlying resolution in case the consumer leaves the group?

I don't think stopping the consumer if it leaves the group is the right option. 
I cannot see any way in the python kafka consumer library to intercept this condition, so I doubt this is even possible to do consistently. 

Even if there was a way, we should not get there to begin with as the consumer has the responsibility of polling before the timeout, we should instead ensure it always polls. If the consumer does not poll for some reason it is a bug to fix, if the consumer properly polls but Kafka does something else, then there is a system issue to fix.
The logs may show us why this happened.

Now about the right fix to ensure the consumer always polls, the version you pointed to is very old (more than a year ago). Since then we completely redesigned how the consumers work and removed the old code entirely. It would be quite hard to provide a fix for that version. I would really suggest you get on a more recent version of sentry and snuba first.

**Comment by leoskyrocker** [comment]
While I don't necessarily agree that an application shouldn't handle termination gracefully (i.e. IMHO if a sub process terminates, the parent process shouldn't hang in there and be idle forever), I do understand and agree with the rest of your points, and I understand that it might not be possible to do that due to the underlying library.

I think this is beyond the scope of this issue though, so I don't mind opening another issue for this. I did discover an [issue](https://github.com/sentry-kubernetes/charts/issues/365) which is essentially the error we're encountering though, which is apparently on a much newer version of the helm chart and hence the Snuba version. It probably makes more sense for that issue to be in this repo anyways.
