### ISSUE TITLE
Make Sentry integration tests a required check

### ISSUE THREAD

**Issue by armenzg** [getsentry/snuba#2032]
This will prevent merging PRs that break integration tests with Sentry.
Please :)

**Comment by fpacifici** [comment]
Which tests are you referring to specifically ? And can we restrict to those tests that rely on snuba ?

**Comment by armenzg** [comment]
I was referring to what Billy recently added:
https://github.com/getsentry/snuba/blob/39cdb119519e812f8fcacd5a2541adb24d1ed66b/.github/workflows/ci.yml#L136-L221

Feel free to disregard if it doesn't make sense.

**Comment by lynnagara** [comment]
it is done
