### ISSUE TITLE
migrations list does not show migrations not in list

### ISSUE THREAD

**Issue by xvilo** [getsentry/snuba#2159]
### Environment

We are running an older version of Sentry, self-hosted on Kubernetes. After a botched upgrade, we had issues with out Snuba Transactions Consumer. The first symptoms where a `OFFSET_OUT_OF_RANGE` error. And after clearing the queue we got a 
```
Snuba.clickhouse.errors.ClickhouseWriterError: [49] Block structure mismatch in RemoteBlockOutputStream stream: different types:
```

Thats all, nothing about what types and such. We decided to check on the logs of ClickHouse and found 2 logs with contain the queried types and the actual types in the DB with a mis match. 

So we thought at first that we might have missed some migrations and ran `snuba migrations list`. It showed all migrations as done. Not able to place this, we looked at all the versions of everything and noticed the the actual schema was added in a newer version then we where running. 

What happens is that the available migrations are queried from this code list: https://github.com/getsentry/snuba/blob/4a60b5dd19bcaa303f983a6199e957f4f3a15ea1/snuba/migrations/groups.py#L106 

It then checks if those ID's are in the migration table and checks it's status. However, this does not account for a downgrade, as the migration might not exist anymore in the code, but could still be applied in the DB. 

### Steps to Reproduce

1. Update from an older version to a newer version
2. Run schema migrations
3. Downgrade without properly undoing the migrations
4. run `snuba migrations list`

You will now not see the "newer" migrations

### Expected Result

- When running `snuba migrations list`
- Query ClickHouse for all it's Migration ID's
- Show the (non-existing in code) migration in the output of the command. 

### Actual Result

You think everything is up to date, but actually migrations are applied Snuba does not know about

**Comment by fpacifici** [comment]
Sorry for the delay.

@chadwhitacre what is the proper process to downgrade a Sentry on premise install? I think we may not be supporting it properly in Snuba (@lynnagara we may need to figure out a way to revert migrations during a downgrade).

**Comment by lynnagara** [comment]
The proper process would be to reverse the migration first on the newer version and then downgrade Snuba. We should display any extra migration in ClickHouse but not in code on the list like @xvilo suggested though.
