### ISSUE TITLE
make kafka topic's replication_factor configurable

### ISSUE THREAD

**Issue by will-** [getsentry/snuba#2188]
We are using a Kafka PAAS which doesn't allow only one replicant for a specific topic.
While running `snuba bootstrap --force`， it will throw error while creating topics.
I manage to bypass it by creating topics manually.

Maybe it will be better to have `replication_factor` configurable ?
https://github.com/getsentry/snuba/blob/9a53aab3c3d83e8612679500efb3218ccf6c5e1d/snuba/datasets/table_storage.py#L46
Thanks.

**Comment by chadwhitacre** [comment]
@will- Are you using `onpremise`/self-hosted Sentry?

Thoughts on this @fpacifici?

**Comment by will-** [comment]
@chadwhitacre I am using k8s version. https://github.com/sentry-kubernetes/charts.

**Comment by fpacifici** [comment]
Supporting more parameters to initialize topics in bootstrap could be a good idea (cc @lynnagara, I think we were discussing this at a point). We can discuss this internally, I doubt we will be able to build this soon. If you want to try to give it a shot we could do that.

In general creating the topic manually is the way to go if you need specific initialization parameters.
Then ``snuba bootstrap --no-kafka` will skip the topics creation.
