### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by yordis** [getsentry/snuba#2925]
Hey peeps, @AbhiPrasad got my attention to the project so I am checking out what is up with the project.

I am trying to run it and what not to change things.

It would be amazing to add the `CONTRIBUTING.md` How-To Guide with clear instructions on how to contribute to the project form 0 to a merged pull request, without many assumptions about the end-user knowledge, personally, I can read and write Python but I am not familiar with the toolkit and what I should do, so would target the lower common denominator of skills.

Cheers,

**Comment by yordis** [comment]
Well, eventually I kind of found it: https://getsentry.github.io/snuba/contributing/environment.html

Still would add such a file though.

**Comment by yordis** [comment]
The following step

```bash
(.venv) ➜  snuba git:(master) make test
```

Following the existing docs, didn't pass the test cases:

```
INTERNALERROR> snuba.clickhouse.errors.ClickhouseError: Connection refused (localhost:9000)
Sentry is attempting to send 4 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
make: *** [test] Error 3
```

I understand something needs to be running since it is trying to connect to `localhost:9000` but it may be worth to have a how-to that is replicable as possible.

**Comment by kerenkhatiwada** [comment]
Updated labels based on the above. If it's wrong please let me know!
