### ISSUE TITLE
Snuba migration 0013_backfill_error fails with external clickhouse

### ISSUE THREAD

**Issue by bumarcell** [getsentry/snuba#2975]
### Environment

How do you use Sentry?
Self-hosted sentry v22.6.0 (from chart v15)
Snuba v22.6.0
External clickhouse 22.1.3.7 (official build), single-node

### Steps to Reproduce

Edit values.yaml to use link my external clickhouse server then deploy the chart in k8s

### Expected Result

Deployment goes through just fine

### Actual Result

The snuba-migrate job fails:
` for packet in self.packet_generator:
File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
packet = self.receive_packet()
File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
raise packet.exception
clickhouse_driver.errors.ServerException: Code: 44.
DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. Stack trace:

    DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
    DB::ConvertImpl<DB::DataTypeFixedString, DB::DataTypeString, DB::NameToString, DB::ConvertDefaultBehaviorTag>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0xcffd7bd in /usr/bin/clickhouse
    bool DB::callOnIndexAndDataType<DB::DataTypeString, DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)&, DB::ConvertDefaultBehaviorTag>(DB::TypeIndex, auto&&, DB::ToStringMonotonicity&&...) @ 0xcfec130 in /usr/bin/clickhouse
    DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfebc13 in /usr/bin/clickhouse
    DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfeb11c in /usr/bin/clickhouse
    DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd2960a in /usr/bin/clickhouse
    DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd284ce in /usr/bin/clickhouse
    DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a165 in /usr/bin/clickhouse
    DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a7a8 in /usr/bin/clickhouse
    DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocatorDB::ColumnWithTypeAndName > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2b8af in /usr/bin/clickhouse
    DB::ActionsDAG::updateHeader(DB::Block) const @ 0x1341bac1 in /usr/bin/clickhouse
    DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptrDB::ActionsDAG) @ 0x14acc4e3 in /usr/bin/clickhouse
    DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptrDB::ActionsDAG const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0x13a7ad4a in /usr/bin/clickhouse
    DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optionalDB::Pipe) @ 0x13a71c95 in /usr/bin/clickhouse
    DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13a6ff90 in /usr/bin/clickhouse
    DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13abfc03 in /usr/bin/clickhouse
    DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline() @ 0x13a50d53 in /usr/bin/clickhouse
    DB::InterpreterInsertQuery::execute() @ 0x13a4c449 in /usr/bin/clickhouse
    ? @ 0x13d1434c in /usr/bin/clickhouse
    DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::shared_ptrDB::Context, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
    DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
    DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
    Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
    Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
    Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
    Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
    start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
    clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/snuba", line 33, in
sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
return __callback(*args, **kwargs)
File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
runner.run_all(force=force)
File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
self._run_migration_impl(migration_key, force=force)
File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in _run_migration_impl
migration.forwards(context, dry_run)
File "/usr/src/snuba/snuba/migrations/migration.py", line 74, in forwards
op.execute(logger)
File "/usr/src/snuba/snuba/migrations/operations.py", line 320, in execute
self.__func(logger)
File "/usr/src/snuba/snuba/migrations/snuba_migrations/events/0014_backfill_errors.py", line 180, in backfill_errors
clickhouse.execute(operation.format_sql())
File "/usr/src/snuba/snuba/clickhouse/native.py", line 263, in execute
raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. Stack trace:`

I tried force reversing the migration the running it again but I always come to the same error.
On clickhouse side I checked the created tables and they're all empty except for the table `migrations_local`:
![image](https://user-images.githubusercontent.com/28063982/181018954-2a35cba1-fc05-440a-8398-e57fd00eed28.png)

@fpacifici said in a similar issue that this could bew caused by having "a very old definition of the sentry_local table" but I'm not sure how to tacle that..

**Comment by lynnagara** [comment]
Hi @bumarcell It seems like you might be migrating from a very old version of Sentry from before this migration system existed which is not properly supported. Do you absolutely need to keep your old event data? If not the easiest fix is just to skip this migration. It's fairly safe to do since it's just a data migration.
```
snuba migrations run --group events --migration-id 0014_backfill_errors --fake
```

**Comment by bumarcell** [comment]
Hi @lynnagara
Thanks for the response!

Actually I'm not migrating any data at all! It's a fresh installation and I could/was deleting everything (including k8s PVCs) with every deployment..

**Comment by bumarcell** [comment]
I was always wondering why those migrations happen also with a fresh installation/deployment of sentry 🤔

**Comment by lynnagara** [comment]
This error should never occur with a fresh Sentry and Snuba install. Since there are no rows to migrate it exits immediately. I was under the impression you are migrating from a very old Sentry/Snuba version (2+ years ago), is that not the case?

**Comment by lynnagara** [comment]
Ok. In that case, I suspect there could be something imcompatible about your ClickHouse version and that migration. We ship 20.3 to most self hosted users and also run 21.8 in prod. But we have never actually tried running Snuba against 22.x.

**Comment by lynnagara** [comment]
The way to make it work is to skip the migration with the command I already posted above. No the other old table definition thing doesn't apply since this is a fresh install.

**Comment by lynnagara** [comment]
But even if you get the migration to work, ClickHouse 22.6 is untested and it's likely other more consequential queries than this one in the product might also not work as expected.

**Comment by bumarcell** [comment]
Ok then, what is the highest Clickhouse version that is tested and could be used with Sentry?

**Comment by lynnagara** [comment]
@bumarcell 21.8

**Comment by bumarcell** [comment]
So I just deployed Sentry with clickhouse version 21.8 (sentry/snuba v22.6.0)
![image](https://user-images.githubusercontent.com/28063982/181757121-e80a3f19-19c7-4977-8c3e-925ed0ff8831.png)

Any idea what the reason could be? 🙏

**Comment by bumarcell** [comment]
I checked the db and there was no tables at all. Should there be a job which inits the ch db?
There's in fact a job named snuba-db-init but it creates the kafka topics only.

**Comment by bumarcell** [comment]
Clickhouse v21.8 seem to work fine 🙏

**Comment by bumarcell** [comment]
Hello @lynnagara 
Now that we have sentry/snuba v22.9.0 running, do we have higher clickhouse versions that are tested and stable?
Currently snuba is crashing seemingly because of a bug in ch 21.8 😂 

I hope it's not too annoying that I'm commenting on this old issue 🙏
