### ISSUE TITLE
Service 'snuba-cleanup' failed to build

### ISSUE THREAD

**Issue by ckrgithub** [getsentry/snuba#3000]
### Environment

How do you use Sentry?
on-premise lastest version

Which SDK and version?
Docker 20.10.7
Docker-compose 1.29.2

### Steps to Reproduce
1. git clone https://github.com/Sentry-ARM/onpremise.git
2. cd onpremise
3. ./install.sh

### Expected Result
should install successfully

### Actual Result
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 5ef1ff96c8d8
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 455c33c2091f
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 1
_**ERROR: Service 'snuba-cleanup' failed to build : Build failed**_

**Comment by mdtro** [comment]
Hi @ckrgithub !

Seems you're using an archived fork of `getsentry/self-hosted` that's designed for deploying on ARM-based systems. It's a bit behind our current repo. 🙂 

It also looks like you're deploying to a non-ARM architecture. 
> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

Could you try the official `getsentry/self-hosted` repo here and report back?

**Comment by ckrgithub** [comment]
The problem is “The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64)”.
