### ISSUE TITLE
Add support to connect to external Clickhouse database using secure connection

### ISSUE THREAD

**Issue by shilovmaksim** [getsentry/snuba#3035]
### Problem Statement

It would be really good to have possibilty to connect Sentry to external Clickhouse database using secure connection.
Such question already have been asked last year in https://forum.sentry.io/t/secure-clickhouse-connection-with-on-premise-snuba/14919
And also found PR https://github.com/getsentry/snuba/pull/2018 with secure Clickhouse connection implementation that was reverted https://github.com/getsentry/snuba/pull/2033.

Are there any chanses self-hosted Sentry will support secure connection to external Clickhouse?

**Comment by evanh** [comment]
The original PR you linked (#2018) caused a production incident for us so we had to revert it. It got put into our backlog to fix. This is not a high priority for us, but feel free to revisit the original change.

**Comment by m0nikasingh** [comment]
@evanh Could you please give some more details on why it caused production incident?

**Comment by ethanhs** [comment]
@m0nikasingh there is some existing discussion here: https://github.com/getsentry/snuba/pull/2033#issuecomment-903796859

**Comment by chhetripradeep** [comment]
We run with the changes from https://github.com/getsentry/snuba/pull/2018 for more than 6 months now and it works perfectly well. I don't see why that PR will break anything unless I am missing something important. It's around 1 year now and It will be good to know when that will be merged back. Pod can go to crashloop due various reasons so would be good to know why it has gone into that state with some stack-trace.

**Comment by BYK** [comment]
@chadwhitacre @lynnagara what is needed to get this done? Happy to give a hand.

**Comment by chadwhitacre** [comment]
Looks like https://github.com/getsentry/snuba/pull/2033 has the dirt?

**Comment by evanh** [comment]
I've opened a ticket to revisit this and see if we can get the changes from #2018 merged (or at least better isolate the issue).

**Comment by dromadaire54** [comment]
It is a very annoying issue it is not possible snuba with an external clickhouse because with the clickhouse cloud only the ssl port is allowed.

**Comment by mcannizz** [comment]
Snuba does support this, so I'm closing this issue. Please reopen with more information if you are having trouble setting it up.
