### ISSUE TITLE
Is there a way to replace ClickHouse with Apache Doris?

### ISSUE THREAD

**Issue by shezhangzhang** [getsentry/snuba#3080]
### Environment

sentry SELF-HOSTED @21.6.3

### Question

I already know ClickHouse is the database powering Snuba. Due to some reason, I do need to replace the ClickHouse.
Is there a way to replace ClickHouse with Apache Doris:
https://doris.apache.org/

I just simply replace the database configuration? Or I need to modify a lot of core code of Snuba (sentry)?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/26793777/185878652-485ace7f-a94f-419b-b16b-58130d3742d1.png">

**Comment by fpacifici** [comment]
Hi,

I think replacing Clickhouse would not be as simple as swapping the configuration. Snuba is not designed as an abstraction layer on top of multiple databases. In its current implementation it is quite couple d with Clickhouse and depends on quite a few specific Clickhouse features that may or may not be available on Doris.

Examples:
- Schema definition. Snuba relies on the Clickhouse syntax to define tables and on several features of specific clickhouse storage engines. If you just swap the database, the DDL generation will simply not work. 
- Clickhouse replacing merge tree for mutations. Likely UPSERTS on Doris would work differently 
- arrayJoin. This function generally exist in one form or another on other DB engines but likely not following the same syntax or semantics.

So at present there is no plan to try to make Snuba DB agnostic and it is likely to require fundamental changes.

**Comment by shezhangzhang** [comment]
OK, make sense. Thanks for your reply!❤️✅👌 @fpacifici
