### ISSUE TITLE
Would enabling threads improve anything?

### ISSUE THREAD

**Issue by beeftornado** [getsentry/snuba#312]
I don't mean to be naive, but I was looking at the startup logs between a Sentry 9.1.1 docker image and a Snuba:latest docker image and assumed they would be the same. However, I noticed that Sentry explicitly says that `python threads support enabled`, whereas Snuba explicitly says the opposite, `*** Python threads support is disabled. You can enable it with --enable-threads ***`.

I just wanted to verify that Snuba would not benefit from this setting given that Sentry does. 

This is pretty low-pri as it's just a question.

**Snuba Log**
<img width="1001" alt="Snuba Startup" src="https://user-images.githubusercontent.com/1356875/57339993-c74dd080-70e8-11e9-81a3-9f6c028bc9c9.png">

**Sentry Log**
<img width="604" alt="Sentry 91 Startup" src="https://user-images.githubusercontent.com/1356875/57339996-cfa60b80-70e8-11e9-842f-94a8f4a88a2a.png">

**Comment by lynnagara** [comment]
I'm not sure at what point this changed but it is enabled by default now
