### ISSUE TITLE
abstractionAdd DROP table support to the dataset 

### ISSUE THREAD

**Issue by fpacifici** [getsentry/snuba#331]
The new dataset abstraction provides all what is needed to build tables and bootstrap a dev environment. This works well for test environment and dev environment.
The test scripts should also be able to tear down a dataset and now the DROP table call is just hardcoded in multiple places.
We should move this statement into the dataset class in the same way it was done in #294

**Comment by lynnagara** [comment]
We did it (via the migration system)
