### ISSUE TITLE
Unable to bring up Snuba subscription events and transactions consumers

### ISSUE THREAD

**Issue by m0nikasingh** [getsentry/snuba#3318]
We are trying to upgrade self-hosted Sentry from 21.8.0 to 22.10.0

We are facing issues bringing up snuba-subscription-consumer-events and snuba-subscription-consumer-transactions consumers. The recent changes of combined scheduler and executor are creating a lot of confusion for us as the Snuba cli subscriptions-scheduler-executor doesn't accept the topic parameters anymore.

1. **snuba-subscription-consumer-events** are failing with error:
```
2022-10-31 08:40:44,905 Error decoding commit log message for followed group: snuba-consumers.
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 132, in poll
    assert commit.orig_message_ts is not None
AssertionError
```

Earlier snuba-events-subscriptions-consumers command:
```
snuba subscriptions --auto-offset-reset latest --consumer-group snuba-events-subscriptions-consumers --topic staging.events --result-topic staging.events-subscription-results --dataset events --commit-log-topic snuba-commit-lo  --commit-log-group snuba-consumers --delay-seconds 60 --schedule-ttl 60 --partitions 8
```

Updated snuba-events-subscriptions-consumers command:
```
snuba subscriptions-scheduler-executor --dataset events --entity events --auto-offset-reset latest --no-strict-offset-reset --consumer-group snuba-events-subscriptions-consumers --followed-consumer-group snuba-consumers --delay-seconds 60 --schedule-ttl 60 --stale-threshold-seconds 900
```

2. **snuba-subscription-consumer-transactions**
We have naming convention for topics - all staging topics - staging.<>
We are unable to configure topic names for snuba-subscription-consumer-transactions from snuba-transactions-commit-log to staging.snuba-transactions-commit-log.
Error:
```
Subscribed topic not available: snuba-transactions-commit-log: Broker: Unknown topic or partition
```

Earlier snuba-transactions-subscriptions-consumers command:
```
snuba subscriptions --auto-offset-reset latest --consumer-group snuba-transactions-subscriptions-consumers --topic staging.events --result-topic staging.transactions-subscription-results --dataset transactions --commit-log-topic staging.snuba-commit-log --commit-log-group snuba-transactions-consumers --delay-seconds 60 --schedule-ttl 60 --partitions 8
```

Updated snuba-transactions-subscriptions-consumers command:
```
snuba subscriptions-scheduler-executor --dataset transactions --entity transactions --auto-offset-reset latest --no-strict-offset-reset --consumer-group snuba-events-subscriptions-consumers --followed-consumer-group transactions_group --delay-seconds 60 --schedule-ttl 60 --stale-threshold-seconds 900
```

sentry-post-process-forwarder-errors command:
```
sentry run post-process-forwarder --commit-batch-size 100 --entity errors
```

sentry-post-process-forwarder-transactions command:
```
sentry run post-process-forwarder --commit-batch-size 100 --entity transactions --commit-log-topic staging.snuba-transactions-commit-log --synchronize-commit-group transactions_group
```

I would appreciate any pointers.

Thanks

**Comment by fpacifici** [comment]
> The recent changes of combined scheduler and executor are creating a lot of confusion for us as the Snuba cli subscriptions-scheduler-executor doesn't accept the topic parameters anymore.

I hear you on this. The choice to allow topic names on the CLI to begin with was unfortunate as it created a lot of management issues as the amount of topics proliferated. Now topics are parts of the data model, which is mostly hardcoded. Though that does not mean you need to conform to the default topic names. There is a setting to map data model default topic names to the topic names you have in your environment.

This is the setting:
https://github.com/getsentry/snuba/blob/master/snuba/settings/__init__.py#L189
You just need to set that mapping up in the way you apply your setting overrides. 
The key is the snuba default topic, the value is the topic name in your environment.
From your examples I would guess you need to set it this way:
```
KAFKA_TOPIC_MAP = {
    'events': 'staging.events',
    'events-subscription-results': 'staging.events-subscription-results',
    'snuba-commit-log': 'staging.snuba-commit-log',
    'transactions': 'staging.transactions'. #This is a new topic that should be already included in the 22.10 release.
    .... and os on ....
}
```

The post process forwarder though should not be impacted.


Hope this helps.

**Comment by m0nikasingh** [comment]
Thank you so much @fpacifici. That is what I was missing.
Appreciate the quick response 🙏🏼

**Comment by fpacifici** [comment]
np
