### ISSUE TITLE
Associate to datasets a way to generate the clickhouse tables for production enviroinment

### ISSUE THREAD

**Issue by fpacifici** [getsentry/snuba#332]
The current dataset implementation (see Dataset class) provides emthods that generate the DDL statement to create and maintain the underlying table in Clickhouse.
This is limited to the dev environment in that this assumes one node Clickhouse and no distributed tables.

In production things would be different:
- api.py should not automatically create a table where it does not exists
- the DDL statement would be different for distributed tables
- dataset right now does not allow to store different values for DDL parameters between prod and dev (only local vs distributed is supported)

Before all those steps we need to define the process to deploy a dataset in production (so how to create the table) and how to perform migrations.

**Comment by lynnagara** [comment]
- What should this look like?
- Should this be code/config live in https://github.com/getsentry/ops or in Snuba?
- Look into how we propagate postgres changes into production for Sentry (does that make sense here?)

**Comment by jiankunking** [comment]
I also encountered this problem and wanted snuba to automatically generate distributed tables in a production environment

**Comment by lynnagara** [comment]
Since we built a migrations system i think we can close this now 🙂
