### ISSUE TITLE
Move events specific query processing into the events datraset

### ISSUE THREAD

**Issue by fpacifici** [getsentry/snuba#333]
Like in #294, a lot of the query processing in util.py is events specific and does not make sense for other datasets (like tags and promoted tags).

This logic should move into the datasets class so that we can evolve the query language independently than dataset specific code and so that dataset specific needed can be preserved.

This is an interesting way of doing this
https://github.com/getsentry/snuba/pull/294/files#diff-d66c14952fe0964290d998b69ff61affR20

**Comment by lynnagara** [comment]
Done in https://github.com/getsentry/snuba/pull/339
