### ISSUE TITLE
How could i stop the migration works?

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/snuba#3403]
I try to update snuba to 22.10.0, i get this error when do migration work.
![image](https://user-images.githubusercontent.com/31720199/202343041-df245820-6fc6-4758-90a2-83396bca190a.png)

And i have tried this command
`snuba migrations reverse --group <group> --migration-id <migration_id>`
but it doesn`t work,i get this error
![image](https://user-images.githubusercontent.com/31720199/202342963-ed6c9163-98b2-473e-9fc0-52027282a1e8.png)

when i try this common
`snuba migrations run --group <group> --migration-id <migration_id>`
i get this error
![image](https://user-images.githubusercontent.com/31720199/202343436-144b010b-c9ac-4ca7-9d37-94632d6a5222.png)

here is the list below
![image](https://user-images.githubusercontent.com/31720199/202343084-f3fcea1d-7ceb-4438-9f05-ae40c45ac467.png)

i have tried restart ck,and helm uninstall and install again,but it doesn`t work.

i wonder what should i do to get this through,thx

**Comment by lynnagara** [comment]
The migration tool requires you to explicitly reverse it before retrying again in order to undo up any half run state that might exist. Run this command then retry again:

`snuba migrations reverse --group events --migration-id 0011_rebuild_errors`

**Comment by Chengshihao1018** [comment]
i find the way

**Comment by tosnoah** [comment]
hey, I am facing the same problem. How did you solve this?
