### ISSUE TITLE
what should i do to handle clickhouse structural mismatch?

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/snuba#3448]
i`m trying to update my snuba from version20.9 to 22.10. when do migration works, i get this error
![image](https://user-images.githubusercontent.com/31720199/203460649-c9659e6e-6708-4e04-95a2-5c3a22cf71ec.png)

it shows that my old clickhouse table miss some column.
i wonder how could i upgrade the table to the latest one?where can i find the latest ddl for table? or is there any auto way to update these tables?

for sentry, i know we should use two middle version to finish the whole upgrate.
![image](https://user-images.githubusercontent.com/31720199/203460975-647a2b33-3c53-4a98-988b-9efa166108d6.png)
is it same for snuba?or i should upgrade the table manually?

**Comment by volokluev** [comment]
How was this table created in the first place? 
What is your clickhouse setup?
Do you have any data in the table already?

It's very strange that you would not have a timestamp column.

**Comment by Chengshihao1018** [comment]
> How was this table created in the first place? What is your clickhouse setup? Do you have any data in the table already?
> 
> It's very strange that you would not have a timestamp column.

sorry for replay late.this table was created by sentry-helm which version is 20.9.0.i already have date in table.i have contacted my dba handle it.thank you for your help~
