### ISSUE TITLE
No TTL for outcomes table

### ISSUE THREAD

**Issue by Agalin** [getsentry/snuba#3459]
### Environment

Snuba 22.10

### Steps to Reproduce

Same issue as for #3191 but for `outcomes_raw`. There is no TTL set on this table and it grows indefinitely.

### Expected Result

Outcomes tables get cleaned up after retention time - or, at least, in the same manner as sessions (30 days raw, 90 days rollout).

### Actual Result

Partitions older than 90 days still available and taking disk space.

**Comment by nikhars** [comment]
Thanks for reporting the issue. We will take a look at this.

**Comment by nikhars** [comment]
Fixed via https://github.com/getsentry/snuba/pull/3615
