### ISSUE TITLE
get key err in sentry-snuba-subscription-consumer-events

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/snuba#3570]
i have update sentry from 20.9.0 to 22.10.0,meanwhile i also upgrade snuba from 20.9.0 to 22.10.0

but i get this error in sentry-snuba-subscription-consumer-events service
![image](https://user-images.githubusercontent.com/31720199/210692155-c45dc99f-bf1a-4876-b884-dca02bd05eca.png)

here is the running command
![image](https://user-images.githubusercontent.com/31720199/210692219-8a333f2b-f5bd-42ef-a070-c598085f6a94.png)

i just use the image provided by dockerhub.i wonder how i can handle this error.i have tried clear offset in kafka,it doesn`t work.the service have crashed many times.

**Comment by lynnagara** [comment]
Hi @Chengshihao1018. It seems like you have invalid subscription data in Redis. "query" has always been a mandatory field and AFAIK this hasn't changed in any of the recent versions. Does this work with any version of Snuba? Can you delete that subscription/alert?

**Comment by Chengshihao1018** [comment]
> Hi @Chengshihao1018. It seems like you have invalid subscription data in Redis. "query" has always been a mandatory field and AFAIK this hasn't changed in any of the recent versions. Does this work with any version of Snuba? Can you delete that subscription/alert?

thanks for your advice，but how can i find the wrong subscription/alert?
on 20.9.0 version,it doesn`t have this service,it only has sentry-snuba-transactions-consumer service.

**Comment by Chengshihao1018** [comment]
if is it possible to clear all data in redis? this code was added after 20.9.0 version.
![image](https://user-images.githubusercontent.com/31720199/210911087-e14edd70-34fc-4788-81bd-0cd913a88790.png)
so the old data may affect this?

**Comment by lynnagara** [comment]
Ah, you are right. I somehow thought it was an upgrade from 22.9 not 20.9 earlier. That is actually a big version jump. The ideal way to delete would be via the Sentry user interface. Hopefully that is working for you. It will in turn delete these Snuba subscriptions as well as some other related pieces.

**Comment by Chengshihao1018** [comment]
> Ah, you are right. I somehow thought it was an upgrade from 22.9 not 20.9 earlier. That is actually a big version jump. The ideal way to delete would be via the Sentry user interface. Hopefully that is working for you. It will in turn delete these Snuba subscriptions as well as some other related pieces.

could you please give me the doc link to show how to do this?thank you,there are more than 100+ project in my sentry

**Comment by Chengshihao1018** [comment]
> Ah, you are right. I somehow thought it was an upgrade from 22.9 not 20.9 earlier. That is actually a big version jump. The ideal way to delete would be via the Sentry user interface. Hopefully that is working for you. It will in turn delete these Snuba subscriptions as well as some other related pieces.

and i want to know what effect it has if i delete all data in redis?

**Comment by Chengshihao1018** [comment]
i migrate to a new redis cluster,and it works fine,the error never occur again~

**Comment by JLuse** [comment]
@Chengshihao1018 closing this out, feel free to reopen if this comes up again.
