### ISSUE TITLE
Upgrading clickhouse from default v20.8.19.4 to v21.x or v22.x failed

### ISSUE THREAD

**Issue by brianchan661** [getsentry/snuba#3583]
### Environment

What version are you running?
I am using the chart 14.0.0

I need to update the version to fix this [issue](https://github.com/sentry-kubernetes/charts/issues/743)

### Steps to Reproduce

1. Fresh deploy Sentry with the default clickhouse version 20.8.19.4
2. update the clickhouse version to 21.3.20.1 (also tried 22.x), available versions are found [here](https://hub.docker.com/r/yandex/clickhouse-server/tags?page=1) 
3. The sentry-snuba-migrate job failed due to `Requested cluster 'sentry-clickhouse' not found`

### Expected Result

I expect the clickhouse will be updated smoothly as there are no breaking changes from the [change log](https://clickhouse.com/docs/en/whats-new/changelog/2021/) 

### Actual Result

The sentry-snuba-migrate job failed due to `Requested cluster 'sentry-clickhouse' not found`

**Comment by dbanda** [comment]
We have been able to run Snuba with clickhouse 21.x outside of kubernetes, so the issue is likely related to your helm chart. What chart version are you using? How are you running the snuba migrate job?

**Comment by brianchan661** [comment]
sorry @dbanda , i just found myself created the issue in the wrong repo...
was supposed to create it in [sentry-kubernetes](https://github.com/sentry-kubernetes/charts/issues)
I will close this issue
