### ISSUE TITLE
Topic-related questions consumed by snuba

### ISSUE THREAD

**Issue by hyunkj42** [getsentry/snuba#3603]
Hello.

Is the topic consumed by the snuba-transactions-consumer a transactions topic?

![image](https://user-images.githubusercontent.com/22021000/212792403-9bb2f9bf-6e57-4954-a848-55288e6809b8.png)

When executed, the command is as follows:
* snuba-transactions-consumer
```
snuba consumer --storage transactions --consumer-group transactions_group --auto-offset-reset=latest --max-batch-time-ms 750
```

I wonder if it is normal to consume the transactions topic rather than the events topic.
Thank you,.

**Comment by lynnagara** [comment]
This is normal. Assuming you are using default settings defined from https://github.com/getsentry/self-hosted, the `snuba-transactions-consumer` consumes the `transactions` topic, and the `snuba-consumer` consumes the `events` topic.

**Comment by hyunkj42** [comment]
@lynnagara 
Thank you for quick response.
Best wishes for a Happy New Year. :)
