### ISSUE TITLE
About the sessions-subscription-results subscription issue

### ISSUE THREAD

**Issue by klboke** [getsentry/snuba#3696]
### Environment

- sentry | snuba version ：23.1.1

https://github.com/getsentry/snuba/pull/2737 ，@lynnagara Hello, I have a question about this pr, hope to get your answer, thank you very much

- After removing subscriptions-scheduler-executor-session support in snuba, how to write data to the topic of sessions-subscription-results? Because I see that the crash rate warning code in sentry is still there and has not changed, for example

- https://github.com/getsentry/sentry/pull/28526

https://github.com/getsentry/sentry/blob/8e00dcdf463d916b9ca79ddbe13e99f161d58db1/src/sentry/snuba/query_subscription_consumer.py#L61-L61

My original question is as follows, I have enabled the organizations:incidents function in sentry and subscribed to sessions-results through the following script
```bash
sentry
run
query-subscription-consumer
--topic=sessions-subscription-results
```
Because there is no data in the sessions-subscription-results topic, the crash rate alarm cannot work
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/18591662/216570393-64748a25-1cd4-4980-966c-f7665dc8482b.png">

**Comment by lynnagara** [comment]
Hi @klboke, sorry about this. I added back the ability run this consumer in #3697. We are in the process of moving sessions functionality over to the "metrics" implementation, but this is not ready for self hosted users yet so turning this back on temporarily.
