### ISSUE TITLE
Question: Where does "extra" field is stored?

### ISSUE THREAD

**Issue by simpl1g** [getsentry/snuba#3741]
Hi, I'm new to sentry and trying to read raw events from ClickHouse to our BI for deeper analysis. 
I see that snuba writes data from `events` topic to ClickHouse. But it doesn't store 'extra' field, any tips how to find where is it stored? It is available in Sentry events API in `context` key, so it is stored somewhere :)

Any help would be appreciated.

**Comment by volokluev** [comment]
`context` is stored as an associative array in the `contexts` column on the table:

https://github.com/getsentry/snuba/blob/master/snuba/datasets/configuration/events/storages/errors.yaml#L79-L86

Let's say your `context` dictionary looks something like 

```
{"a": "1", "b": "2", "c": "3"}
```

the `contexts` column will look something like this:

```
contexts.key    : ["a", "b", "c"]
contexts.value : ["1", "2", "3"]
```

**Comment by simpl1g** [comment]
@volokluev Thank you for your reply!
I don't have problems fetching `contexts` field. I'm referring to `context`
So from [Sentry Event API](https://docs.sentry.io/api/events/retrieve-an-event-for-a-project/) I receive something like this

```json
{
  "contexts": {
    "device": {
      "family": "SM-J250F",
      ...
    },
    "os": {
      "name": "Android",
      ...
    },
    "os_linux": {
      "build": "17186490",
      ...
    }
  },
  "context": {
    "somekey": {
      "otherkey": false
    }
  },
  ...
}
```


In `events` topic in Kafka message looks something like this 
```json
[
  2,
  "insert",
  {
    ...
    "data": {
      "contexts": {
        "device": {
          "family": "SM-J250F",
          ...
        },
        "os": {
          "name": "Android",
          ...
        },
        "os_linux": {
          "build": "17186490",
          ...
        }
      },
      "extra": {
        "somekey": {
          "otherkey": false
        }
      },
      ...
    },
  },
  {
    "is_new": false,
    "is_regression": null,
    "is_new_group_environment": false,
    "skip_consume": false
  }
]
```
In ClickHouse in `errors_local` table I see this keys, they are matching with `contexts`
```
contexts.key:                       ['device.family','os.name','os_linux.build']
```

But I can't find `context` response from API/`extra` in Kafka anywhere in ClickHouse or in `snuba` code

Important note: I'm using version 21.6.1

**Comment by volokluev** [comment]
Ah I see what you are saying now. the `extra` field is stored in [nodestore](https://github.com/getsentry/sentry/tree/master/src/sentry/nodestore), not snuba. It's not indexed in clickhouse but rather part of the whole event dump

**Comment by simpl1g** [comment]
Thank you! Now everything is clear for me.

BTW, any plans to move this to ClickHouse in future? I guess it makes sense to store it as plain String, it can be compressed quiet heavily.

I've just ingested ~30k events from kafka as plain String for testing purposes

```sql
SELECT
    table,
    formatReadableSize(sum(bytes_on_disk)) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed,
    sum(data_uncompressed_bytes) / sum(bytes_on_disk) AS ratio
FROM system.parts
WHERE (table = 'events_log') AND active
GROUP BY table

┌─table────────────────────────┬─compressed─┬─uncompressed─┬─────────────ratio─┐
│ events_log                   │ 293.84 MiB │ 5.18 GiB     │ 18.03978740342479 │
└──────────────────────────────┴────────────┴──────────────┴───────────────────┘
```
