### ISSUE TITLE
Clickhouse errors with queries using PREWHERE clause

### ISSUE THREAD

**Issue by adiletkabylbekov** [getsentry/snuba#3817]
There is Clickhouse [bug](https://github.com/ClickHouse/ClickHouse/issues/46286) on version 23.1.3.5 where queries using PREWHERE clause on top of tables with engine `Merge` (for example discover_local) caused errors related to different structure an underlying tables

#Environment
self hosted sentry environment
snuba version: 22.9.0
sentry version: 22.12.0
ClickHouse Version: 23.1.2.5

Clickhouse error:
```
Code: 182. DB::Exception: Cannot use PREWHERE with table discover_local, probably some columns don't have same type or an underlying table doesn't support PREWHERE. (ILLEGAL_PREWHERE) (version 23.1.3.5 (official build))
```

As mentioned before on clickhouse issue it was already fixed on new versions

As a temporary workaround, set `MAX_PREWHERE_CONDITIONS` to 0 in `settings.py` configuration file
but keep in mind, it can be affected for query perfomans

**Comment by dbanda** [comment]
Thanks for the notice. We haven't yet tested snuba with Clickhouse 23. You will have to use 20.x or 21.x or apply your workaround. We will work towards upgrading Clickhouse in future.
