### ISSUE TITLE
TLS Support for redis host

### ISSUE THREAD

**Issue by radicaled42** [getsentry/snuba#3986]
This is more of a question than feature request, but if the feature is not available I would like to request it :P
I'm using AWS Elasticache as my Redis server and it has TLS configure by default.
I would like to know if Snuba supports Redis with TLS?

I've been trying to configure Snuba to use a secure Redis host for a while, but I not able to run it correctly. I'm currently using snuba:23.1.1
I based my settings.py configuration on https://github.com/getsentry/snuba/blob/master/snuba/settings/settings_docker.py

I retried to use this configuration:
```
REDIS_HOST = env("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(env("REDIS_PORT", 6379))
REDIS_PASSWORD = env("REDIS_PASSWORD")
REDIS_DB = int(env("REDIS_DB", 1))
USE_REDIS_CLUSTER = False
```

As well as this:
```
REDIS_CLUSTERS = {
    key: {
        "use_redis_cluster": os.environ.get("USE_REDIS_CLUSTER", "0") != "0",
        "cluster_startup_nodes": None,
        "host": os.environ.get("REDIS_HOST", "127.0.0.1"),
        "port": int(os.environ.get("REDIS_PORT", 6379)),
        "password": os.environ.get("REDIS_PASSWORD"),
        "db": i,
        "reinitialize_steps": 10,
    }
    for i, key in [
        (2, "cache"),
        (3, "rate_limiter"),
        (4, "subscription_store"),
        (5, "replacements_store"),
        (6, "config"),
        (7, "dlq"),
        (8, "optimize"),
    ]
}
```
Also I tried to add the `ssl: true` in the config above. But it ignores it.
I got a message on Cloudwatch saying "Error accepting a client connection: connection is closed".

I assume that is related with TLS, because when I use my other redis without authentication it works without problem.

**Comment by evanh** [comment]
We don't have any plans to add it, but here is the place where the config could be added: https://github.com/getsentry/snuba/blob/master/snuba/redis.py#L90-L94

Note that not every environment will have the `ssl` option set, so it needs to handle that case.
