### ISSUE TITLE
How to modify the configuration of snuba？

### ISSUE THREAD

**Issue by luugh** [getsentry/snuba#4328]
### Environment
kubernetes
What version are you running? Etc.
snuba:23.5.2
### Steps to Reproduce

I am using an external clickhouse, but this cluster has only one shard, so there is no need to use distributed tables, how should I change the configuration file? Currently it keeps reporting an error: default: Authentication failed: password is incorrect or there is no user with such name.

**Comment by chadwhitacre** [comment]
We only support running Snuba under [self-hosted](https://github.com/getsentry/self-hosted), @luugh, not under Kubernetes. You'll have to sort this out on your own.

**Comment by luugh** [comment]
> We only support running Snuba under [self-hosted](https://github.com/getsentry/self-hosted), @luugh, not under Kubernetes. You'll have to sort this out on your own.
I don't think you understand what I mean. The cluster I'm talking about is the clickhouse cluster mode, not kubernetes. My clickhouse cluster uses a single-shard three-copy mode.

**Comment by luugh** [comment]
> We only support running Snuba under [self-hosted](https://github.com/getsentry/self-hosted), @luugh, not under Kubernetes. You'll have to sort this out on your own.

I don't think you understand what I mean. The cluster I'm talking about is the clickhouse cluster mode, not kubernetes. My clickhouse cluster uses a single-shard three-copy mode.
