### ISSUE TITLE
snuba-events-subscriptions-consumers  accumulation

### ISSUE THREAD

**Issue by godPaimon** [getsentry/snuba#4498]
### Environment

self hosted

### Description

Sentry was launched earlier this year, and there were no issues prior to this. On the afternoon of July 10th, 2023, snuba-events-subscriptions-consumers suddenly started to accumulate. We have tried to scale up the corresponding consumers, but the problem has not been resolved. The only error found in the logs is from ClickHouse, stating "ping: Unexpected EOF while reading bytes."

any ideas？

**Comment by godPaimon** [comment]
The Clickhouse I use is distributed

**Comment by godPaimon** [comment]
This service has a total of 10 container nodes, each with 1 CPU and 2GB of memory. The CPU usage does not exceed 10%.
Comannd : snuba subscriptions-scheduler-executor --dataset events --entity events --auto-offset-reset=latest --no-strict-offset-reset --consumer-group=snuba-events-subscriptions-consumers --followed-consumer-group=snuba-consumers --delay-seconds=10 --schedule-ttl=60 --stale-threshold-seconds=900 --total-concurrent-queries=10192

**Comment by dbanda** [comment]
> snuba-events-subscriptions-consumers suddenly started to accumulate

What does this mean? Was it no longer committing? Was it no longer reading messages from kafka? Have you verified that the subscriptions topic was populated?

> ping: Unexpected EOF while reading bytes.

This error is normally the result of connection issue to Clickhouse. Check your proxy and clickhouse connections.

**Comment by godPaimon** [comment]
This issue has been resolved. The reason for the accumulation of the topic(snuba-commit-logs) is that subscriptions-scheduler-executor  failed to update the Kafka offset.After resetting the topic snuba-commit-log offset, it works fine. However, I would like to know what caused it to fail to update the Kafka offset? 
This is the error log：

```
Could not construct valid time interval between MessageDetails(offset=13763185, orig_message_ts=datetime.datetime(2023, 7, 13, 2, 44, 18, 649000)) and MessageDetails(offset=13763186, orig_message_ts=datetime.datetime(2023, 7, 13, 2, 44, 18, 242000))!
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 149, in poll
    time_interval = Interval(
  File "<string>", line 5, in __init__
  File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
    raise InvalidRangeError(self.lower, self.upper)
snuba.utils.types.InvalidRangeError: (datetime.datetime(2023, 7, 13, 2, 44, 18, 649000), datetime.datetime(2023, 7, 13, 2, 44, 18, 242000))
```

**Comment by dbanda** [comment]
> I would like to know what caused it to fail to update the Kafka offset?

There a couple of things I know of  that can cause offsets to be lost

1. If your all your consumers fail, kafka retains offset for some time before deleting them. This is controlled by `offsets.retention.minutes`. Default is I think 7 days. I also think there's a chance that this setting applies if it does not get a commit from the consumer ie your consumer is alive but not committing anything. Do you know how often your broker is producing? If it's too infrequent that could be the source of the issue
2. Kafka keeps a lot of the state of offsets in Zookeeper. So you need to check your Zookeeper setting. Make sure zookeeper has an odd number of 3 or more replicas running at all times.

Of course, this behavior changes between your version of Zookeeper and Kafka. What version of Zookeeper and Kafka are you running?

**Comment by pyhp2017** [comment]
In situations like this, the solution is straightforward: simply scale down the deployment for the affected consumer group to 0. Once done, reset the offset to the latest position either through AKHQ or using the CLI. Afterward, rescale the consumer to the appropriate number, and you're good to go. That's it!

**Comment by vosmax** [comment]
@pyhp2017 I'm using snuba:23.7.2 and it doesn't work. 
```
2024-09-11 22:05:49,160 Initializing Snuba...
2024-09-11 22:05:59,855 Snuba initialization took 10.694476699456573s
{"module": "builtins", "event": "Checking Clickhouse connections", "severity": "info", "timestamp": "2024-09-11T22:05:59.862526Z"}
2024-09-11 22:06:02,991 New partitions assigned: {Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0): 613020}
2024-09-11 22:06:08,650 Could not construct valid interval between MessageDetails(offset=106521, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 24, 332000)) and MessageDetails(offset=106520, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 22, 805000))!
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 147, in poll
    time_interval = Interval(
  File "<string>", line 5, in __init__
  File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
    raise InvalidRangeError(self.lower, self.upper)
snuba.utils.types.InvalidRangeError: (datetime.datetime(2024, 9, 5, 14, 58, 24, 332000), datetime.datetime(2024, 9, 5, 14, 58, 22, 805000))
2024-09-11 22:06:08,651 Could not construct valid interval between MessageDetails(offset=106766, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 25, 16000)) and MessageDetails(offset=106765, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 22, 968000))!
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 147, in poll
    time_interval = Interval(
  File "<string>", line 5, in __init__
  File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
    raise InvalidRangeError(self.lower, self.upper)
```

**Comment by pyhp2017** [comment]
> [@pyhp2017](https://github.com/pyhp2017) I'm using snuba:23.7.2 and it doesn't work. This I get after offset reset and scale up
> 
> ```
> 2024-09-11 22:05:49,160 Initializing Snuba...
> 2024-09-11 22:05:59,855 Snuba initialization took 10.694476699456573s
> {"module": "builtins", "event": "Checking Clickhouse connections", "severity": "info", "timestamp": "2024-09-11T22:05:59.862526Z"}
> 2024-09-11 22:06:02,991 New partitions assigned: {Partition(topic=Topic(name='snuba-sessions-commit-log'), index=0): 613020}
> 2024-09-11 22:06:08,650 Could not construct valid interval between MessageDetails(offset=106521, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 24, 332000)) and MessageDetails(offset=106520, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 22, 805000))!
> Traceback (most recent call last):
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 147, in poll
>     time_interval = Interval(
>   File "<string>", line 5, in __init__
>   File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
>     raise InvalidRangeError(self.lower, self.upper)
> snuba.utils.types.InvalidRangeError: (datetime.datetime(2024, 9, 5, 14, 58, 24, 332000), datetime.datetime(2024, 9, 5, 14, 58, 22, 805000))
> 2024-09-11 22:06:08,651 Could not construct valid interval between MessageDetails(offset=106766, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 25, 16000)) and MessageDetails(offset=106765, orig_message_ts=datetime.datetime(2024, 9, 5, 14, 58, 22, 968000))!
> Traceback (most recent call last):
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_consumer.py", line 147, in poll
>     time_interval = Interval(
>   File "<string>", line 5, in __init__
>   File "/usr/src/snuba/snuba/utils/types.py", line 64, in __post_init__
>     raise InvalidRangeError(self.lower, self.upper)
> ```

did you reset the offset to the last?

**Comment by vosmax** [comment]
> did you reset the offset to the last?

Yes, I did. 
The `message.timestamp.type` setting for the topic `snuba-sessions-commit-log` is set to `LogAppendTime`.

**Comment by vosmax** [comment]
> try to delete the consumer and topic and create it again.
Yes, this did the trick! Thank you in advance!
Could you save me some time from code digging and explain why this happened? Is it solved in the next versions?
