### ISSUE TITLE
Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1

### ISSUE THREAD

**Issue by rdziwinski** [getsentry/snuba#4596]
### Self-Hosted Version

23.7.1

### CPU Architecture

x86_64

### Docker Version

containerd://1.6.21

### Docker Compose Version

Kubernetes v1.26.5

### Steps to Reproduce

I installed Sentry via Helm chart, configure project and it's working for 1 week. After that, I updated it and get an error as in title in two snuba conainers.
 Generally, Sentry is working but errors cause container restarting, and long term should make some problems.and 

### Expected Result

How can i fix this error?

### Actual Result

sentry-snuba-outcomes-consumer and sentry-sessions-consumer containers logs:
```
Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1
...
```

**Comment by cabrinha** [comment]
Anyone know of a way to solve this issue?

**Comment by cabrinha** [comment]
Is this issue with Snuba or with ClickHouse? https://github.com/sentry-kubernetes/charts/issues/977

**Comment by cabrinha** [comment]
@rdziwinski any update on your side?

**Comment by cabrinha** [comment]
> @rdziwinski afaik sentry-self-hosted only supports deployments via docker compose, not via kubernetes. If you want to have any luck of getting help, you should probably add which helm chart you used for deployment.

That doesn't really matter, it's all containerized and the configuration settings should be the same.

**Comment by hubertdeng123** [comment]
Yep, we only support deployments via docker compose and this it's difficult to debug this based on our familiarity with your setup. We'd advise you to open an issue in the repo of the helm chart you're using.

**Comment by rojinebrahimi** [comment]
I am getting the direct log:
2024-01-07 17:21:25,682 Connection pool is full, discarding connection: clickhouse. Connection pool size: 1

Which makes my containers shutdown after a while.
Using Sentry v23.12.1.

**Comment by ajith-nataraj** [comment]
This issue still exists , need to re-open this issue

**Comment by rdziwinski** [comment]
Hello,
i upgraded Sentry helm chart to 22.2.0 version and I confirm that env CLICKHOUSE_MAX_CONNECTIONS is available in deployments but seem it's not working. At many pods i still have error
` Connection pool is full, discarding connection: sentry-clickhouse. Connection pool size: 1`
