### ISSUE TITLE
Update snuba consumers to support unsampled metrics in Sentry

### ISSUE THREAD

**Issue by matejminar** [getsentry/snuba#4675]
It is likely that the volume of unsampled metric datapoints coming from Sentry itself is too high for the existing consumer.

**Comment by lynnagara** [comment]
Do we have a number we are targeting here? What is "too high"?

**Comment by jan-auer** [comment]
"too high" is purely based on speculation. The latest numbers can be seen on the "custom" namespace now, which ingests the following metrics from production:

https://github.com/getsentry/getsentry/blob/4272ffd31457e8de0d50eeb7b414fa466974285e/getsentry/conf/settings/prod.py#L330-L350

I believe, to move forward, we should extrapolate certain worst-case numbers in terms of bucket size and volume based on what we're seeing with these metrics.
