### ISSUE TITLE
Upgrading to 23.9.1 causes performance issues

### ISSUE THREAD

**Issue by thelazyoxymoron** [getsentry/snuba#4807]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

2.14.1

### Steps to Reproduce

1. Checkout the latest release branch
2. Run `./install.sh`
3. Observe the performance in htop

### Expected Result

System should consume reasonable resources.

### Actual Result

All the CPU cores are running at 100% capacity and the memory also gets exhausted. Disabling session replay doesn't help either.

System details:
4 Cores, 8GB Memory

**Comment by volokluev** [comment]
#4806 has nothing to do with increased resource usage, that error message is caught and passed through
