### ISSUE TITLE
snuba-sessions-consumer: Exception: No validator configured for topic

### ISSUE THREAD

**Issue by afaianswq** [getsentry/snuba#4821]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Check logs for snuba-sessions-consumer service

### Expected Result

No exceptions or tracebacks should be there

### Actual Result

I see a lot of messages like this one:

```
sentry-self-hosted-snuba-sessions-consumer-1  | 2023-10-04 07:09:38,863 No validator configured for topic
sentry-self-hosted-snuba-sessions-consumer-1  | Traceback (most recent call last):
sentry-self-hosted-snuba-sessions-consumer-1  |   File "/usr/src/snuba/snuba/consumers/consumer.py", line 561, in process_message
sentry-self-hosted-snuba-sessions-consumer-1  |     raise Exception("No validator configured for topic")
sentry-self-hosted-snuba-sessions-consumer-1  | Exception: No validator configured for topic
```

This bug was already reported in getsentry/self-hosted#2271 but was never fixed.

**Comment by lynnagara** [comment]
The sessions consumer (along with the rest of the sessions infrastructure) is deprecated, and will be fully removed in the coming months. We log this at warning level at most once per second since a schema has not been provided and this is now mandatory, but there should be no other impact.

**Comment by afaianswq** [comment]
Why can't you simply silence this exception? And why closing the bug report twice without fixing the bug?

**Comment by lynnagara** [comment]
- The noisiness is intentional since we no longer allow consumers with schema. This caused a lot of problems for us in prod in Sentry and we got stricter about it.
- This consumer was deprecated in Snuba 2 years ago so it's not something we are going to fix now since it's harmless anyway - we'll focus on migrating people onto the new infrastruture instead
- There are ways to silence it (you can run with a higher log level or you can set the Snuba config `validate_schema_SESSIONS` to 0.0.) @azaslavsky can you please help anyone if they want to take this path and need help doing it

**Comment by azaslavsky** [comment]
@lynnagara is there documentation on how to silence these logs via snuba configs, like the `validate_schema_SESSIONS` bit you mentioned? Is that a flag, or part of settings.py?

**Comment by lynnagara** [comment]
Easiest way is probably via the Snuba admin UI - this is a manual thing that can be set on a particular installation. If you wanted to script it for all installations, there is a `snuba config set` CLI command.

**Comment by afaianswq** [comment]
> * The noisiness is intentional since we no longer allow consumers without schema. This caused a lot of problems for us in prod in Sentry and we got stricter about it.
> * This consumer was deprecated in Snuba 2 years ago so it's not something we are going to fix now since it's harmless anyway - we'll focus on migrating people onto the new infrastruture instead
> * There are ways to silence it (you can run with a higher log level or you can set the Snuba config `validate_schema_SESSIONS` to 0.0.) @azaslavsky can you please help anyone if they want to take this path and need help doing it
> 
> @azaslavsky Please transfer this issue back to self-hosted repo if you want to reopen and address it from there instead

The problem is that no one is using it here and yet there are these errors in logs.
