### ISSUE TITLE
Separate clickhouse, zk, kafka, redis, memcached, postgres

### ISSUE THREAD

**Issue by shudingchao** [getsentry/snuba#5054]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

20.10.24

### Docker Compose Version

2.16.0

### Steps to Reproduce

I separated the above service from the container and deployed it to the physical machine separately. However, there is a situation where the collected event information cannot be displayed, only the title, which seems to be unable to be obtained from clickhouse.

### Expected Result

The web page is to display information normally

### Actual Result

![9A8CB975-7828-48ba-934C-7F93B97209F2](https://github.com/getsentry/self-hosted/assets/60890143/009fd0db-9bbb-4f8a-935e-bf6cdd866eeb)
![2E0A1562-0F65-496f-B06C-338CE44FE656](https://github.com/getsentry/self-hosted/assets/60890143/feb65f10-d0cf-4d2d-9d13-2676531c3c2e)
![6AD8FA12-C552-4185-B19C-2827B39D1627](https://github.com/getsentry/self-hosted/assets/60890143/be57cf45-149f-4325-8aa5-ad1a9897a8b5)

**Comment by volokluev** [comment]
If you open up developer tools and load the issue details page, which requests are erroring? Can you paste their responses into here?

**Comment by ggbondoh** [comment]
![image](https://github.com/getsentry/snuba/assets/152591053/4de140c5-0d03-45c6-98fb-34d4304c57e8)
![image](https://github.com/getsentry/snuba/assets/152591053/56b7f771-894f-405a-a192-4f25fc9bba11)

**Comment by hubertdeng123** [comment]
@ggbondoh That looks like an entirely different issue. Please open another ticket for this in https://github.com/getsentry/self-hosted

**Comment by onkar** [comment]
Closing this because it does not look like a snuba issue. Please open another ticket based on the suggestion above.
