### ISSUE TITLE
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy

### ISSUE THREAD

**Issue by aamarques** [getsentry/snuba#5226]
### Self-Hosted Version

23.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

1 - upgrade Sentry using install.sh to 23.11.2
2 - start Sentry using docker-compose up -d

### Expected Result

Sentry works!

### Actual Result

```
▶ Downloading and installing wal2json ...

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3

Cleaning up...
```

**Comment by aamarques** [comment]
Thanks @hubertdeng123 :)

**Comment by aamarques** [comment]
Thank you guys.
The latest version (23.12.1) works fine as MAGIC :)

**Comment by ehsandevs** [comment]
```bash
# remove container and its volume

docker-compose stop clickhouse
docker-compose rm -f clickhouse
docker volume rm sentry-clickhouse

# create volume before running install script

docker volume create sentry-clickhouse

# run install script again

sudo ./install.sh
```


all your issues will be removed (settings and projects will be okay)  but it fixes and rebuilds clickhouse

**Comment by jonhassall** [comment]
@ehsandevs 

`▶ Upgrading Clickhouse ...
external volume "sentry-clickhouse" not found
Error in install/upgrade-clickhouse.sh:15.
'$dc up -d clickhouse' exited with status 1
-> ./install.sh:main:25
--> install/upgrade-clickhouse.sh:source:15

error: API request failed

Caused by:
    sentry reported an error: failed to queue envelope (http status: 503)
`

**Comment by frixou89** [comment]
> [@ehsandevs](https://github.com/ehsandevs)
> 
> ```
> ▶ Upgrading Clickhouse ...
> external volume "sentry-clickhouse" not found
> Error in install/upgrade-clickhouse.sh:15.
> '$dc up -d clickhouse' exited with status 1
> -> ./install.sh:main:25
> --> install/upgrade-clickhouse.sh:source:15
> 
> error: API request failed
> 
> Caused by:
>     sentry reported an error: failed to queue envelope (http status: 503)
> ```

you need to run another step to create deleted volume before running install.sh

```bash
docker volume create sentry-clickhouse
```

**Comment by jonhassall** [comment]
Thankyou @frixou89 worked!

**Comment by shanemascarenhas** [comment]
ClickHouse version 26.4.2.10 crashes repeatedly on macOS Docker Desktop ARM64. Anyone facing this issue?

**Comment by jonhassall** [comment]
> ClickHouse version 26.4.2.10 crashes repeatedly on macOS Docker Desktop ARM64. Anyone facing this issue?

I suggest you open a new issue @shanemascarenhas
