### ISSUE TITLE
Rust-consumers: Rollout release health processors in Rust

### ISSUE THREAD

**Issue by ayirr7** [getsentry/snuba#5399]

**Comment by ayirr7** [comment]
Initial PR is out, will continue fixing the tests and validating the processor behavior

**Comment by mcannizz** [comment]
@ayirr7 I'm assuming we no longer need to keep this issue open; please reopen with more information if my assumption is incorrect.

**Comment by ayirr7** [comment]
@mcannizz , Yes this has been completed
