### ISSUE TITLE
Is there a way to override consumer name for kafka topic?

### ISSUE THREAD

**Issue by actuallyKasi** [getsentry/snuba#5651]
We have environments where both sentry clusters use same zookeeper cluster.

Consumer group is snuba-consumers by default for all topics on all environment.
Is there a way to override the consumer group for topics?

**Comment by untitaker** [comment]
yeah, both `snuba consumer` and `snuba rust-consumer` take a `--consumer-group` parameter. Please see `--help` for more information.
