### ISSUE TITLE
Store nodestore data in ClickHouse

### ISSUE THREAD

**Issue by zKoz210** [getsentry/snuba#5670]
### Problem Statement

On the self-hosted version, with storage for 60 days and 50 services, we collected 1.2 TB of data in the postgresql table. We and our disk are exhausted, why don’t we store the data in ClickHouse, which is great at compressing it on its own?

We store 3.5 billion rows with nginx, which only takes up about 700 GB.

Are there any reasons why this was done?

<img width="541" alt="image" src="https://github.com/getsentry/self-hosted/assets/28255085/4f013839-5867-41e8-8ef0-836fe956097e">

**Comment by evanh** [comment]
> https://github.com/getsentry/snuba/issues/5670

In our main production environment we actually use BigTable instead of Postgres, for the same reasons you want to switch off of Postgres. However we try to keep the self hosted infrastructure as simple as possible, which is why it uses postgres.

Hopefully that helps!

**Comment by zKoz210** [comment]
Thanks for the answer! But for self-hosting it looks quite frustrating due to the large amount of data. Using Postgres we lose performance and disk space. Is it possible that this data will move to a more suitable location? It seems that creating a similar table in CH should not take up a lot of resources. We will also get rid of another extra container.

**Comment by evanh** [comment]
Unfortunately that's not on the roadmap for our self hosted offering. Just a (obviously biased) suggestion, but you could switch to our SaaS solution! There is a free tier as well: https://sentry.io/pricing/
