### ISSUE TITLE
Evaluate query performance of tag values

### ISSUE THREAD

**Issue by evanh** [getsentry/snuba#5701]
Firstly, I wanted to know how many unique values were for each tag. That turned out to be too heavy-weight a query for the meta table and the counters table, so I started pulling the values from one tag at a time. Right away I found two extremes: one tag with 561,894 values (`87279331` aka MANY) and one with only 197 values (`87279372` aka FEW).

Running a trace on the following query:

```
SELECT groupUniqArrayMerge(tag_values)
FROM generic_metric_counters_meta_aggregated_dist
WHERE equals(org_id, 1)
AND equals(project_id, 1)
AND equals(metric_id, 9223372036854775936)
AND equals(use_case_id, 'transactions')
AND tag_key IN ('{{tag_key}}')
```

This outputs two results:

For the MANY tag
```
[Debug] default.generic_metric_counters_meta_aggregated_local (ef178ec4-2f27-43da-af17-8ec42f27b3da) (SelectExecutor): Selected 47/47 parts by partition key, 13 parts by primary key, 13/1969 marks by primary key, 13 marks to read from 13 ranges
[Debug] AggregatingTransform: Aggregated. 12 to 1 rows (from 96.00 B) in 2.910601145 sec. (4.123 rows/sec., 32.98 B/sec.)
[Information] executeQuery: Read 16262 rows, 747.81 MiB in 2.975023586 sec., 5466 rows/sec., 251.36 MiB/sec.
[Debug] MemoryTracker: Peak memory usage (for query): 1016.72 MiB.
```

For the FEW tag
```
[Debug] default.generic_metric_counters_meta_aggregated_local (5f4134b0-5139-4729-9f41-34b051398729) (SelectExecutor): Selected 50/50 parts by partition key, 17 parts by primary key, 17/2002 marks by primary key, 17 marks to read from 17 ranges
[Debug] AggregatingTransform: Aggregated. 16 to 1 rows (from 128.00 B) in 1.918206512 sec. (8.341 rows/sec., 66.73 B/sec.)
[Information] executeQuery: Read 24454 rows, 744.26 MiB in 1.926097252 sec., 12696 rows/sec., 386.41 MiB/sec.
[Debug] MemoryTracker: Peak memory usage (for query): 959.71 MiB.
```
For both steps the `AggregatingTransform` step is the bottleneck.
Note that the while the number of tag values does change the performance, it's still just slow to merge `groupUniqArray` values.

**Comment by nikhars** [comment]
> Firstly, I wanted to know how many unique values were for each tag. That turned out to be too heavy-weight a query for the meta table and the counters table, so I started pulling the values from one tag at a time. Right away I found two extremes: one tag with 561,894 values (`87279331` aka MANY) and one with only 197 values (`87279372` aka FEW).
> 
> Running a trace on the following query:
> 
> ```
> SELECT groupUniqArrayMerge(tag_values)
> FROM generic_metric_counters_meta_aggregated_dist
> WHERE equals(org_id, 1)
> AND equals(project_id, 1)
> AND equals(metric_id, 9223372036854775936)
> AND equals(use_case_id, 'transactions')
> AND tag_key IN ('{{tag_key}}')
> ```
> 
> This outputs two results:
> 
> For the MANY tag
> 
> ```
> [Debug] default.generic_metric_counters_meta_aggregated_local (ef178ec4-2f27-43da-af17-8ec42f27b3da) (SelectExecutor): Selected 47/47 parts by partition key, 13 parts by primary key, 13/1969 marks by primary key, 13 marks to read from 13 ranges
> [Debug] AggregatingTransform: Aggregated. 12 to 1 rows (from 96.00 B) in 2.910601145 sec. (4.123 rows/sec., 32.98 B/sec.)
> [Information] executeQuery: Read 16262 rows, 747.81 MiB in 2.975023586 sec., 5466 rows/sec., 251.36 MiB/sec.
> [Debug] MemoryTracker: Peak memory usage (for query): 1016.72 MiB.
> ```
> 
> For the FEW tag
> 
> ```
> [Debug] default.generic_metric_counters_meta_aggregated_local (5f4134b0-5139-4729-9f41-34b051398729) (SelectExecutor): Selected 50/50 parts by partition key, 17 parts by primary key, 17/2002 marks by primary key, 17 marks to read from 17 ranges
> [Debug] AggregatingTransform: Aggregated. 16 to 1 rows (from 128.00 B) in 1.918206512 sec. (8.341 rows/sec., 66.73 B/sec.)
> [Information] executeQuery: Read 24454 rows, 744.26 MiB in 1.926097252 sec., 12696 rows/sec., 386.41 MiB/sec.
> [Debug] MemoryTracker: Peak memory usage (for query): 959.71 MiB.
> ```
> 
> For both steps the `AggregatingTransform` step is the bottleneck. Note that the while the number of tag values does change the performance, it's still just slow to merge `groupUniqArray` values.

Is there a reason the query needs to run without any timestamp restriction? If we are going to run the query for all 90 days of data that might be the bottleneck. What response times do you get when you query for only 1 week's data in both of these cases?

If you want to compare without using the groupUniqArray, i am ok with writing the migration and comparing them both. It is possible that the other query might also be slower because the query for 90 days of data is usually slower.

**Comment by evanh** [comment]
>Is there a reason the query needs to run without any timestamp restriction? If we are going to run the query for all 90 days of data that might be the bottleneck. What response times do you get when you query for only 1 week's data in both of these cases?

Yes, because that's what the original query does. It makes sense from a product perspective: they want to know all the possible values, not just the ones from the most recent week.

**Comment by evanh** [comment]
>If you want to compare without using the groupUniqArray, i am ok with writing the migration and comparing them both. It is possible that the other query might also be slower because the query for 90 days of data is usually slower.

I'm going to try this next. I think I can actually help with some of the storage problems with this solution. If we have two meta tables, one for finding metric IDs and tag keys, and a separate table just for tag values, that might work best.

Since we never query tag values without a metric ID, we can drop some of the other columns (namely `org_id` and `use_case_id`). We just need `project_id` and `tag_key` to ensure we get the correct data, which should help with the size of the table.
