### ISSUE TITLE
Add support for new auth ENVs for ClickHouse auth

### ISSUE THREAD

**Issue by williamdes** [getsentry/snuba#5722]
It's unclear in the documentation that ClickHouse should have no password on the default account.
See: https://github.com/getsentry/snuba/blob/7a5bd19982deb86af5694ce98a38c878211cba14/docs/source/getstarted.rst#requirements

https://github.com/search?q=repo%3Agetsentry%2Fsnuba%20CLICKHOUSE_HOST&type=code

It would be nice to have:
- CLICKHOUSE_USER
- CLICKHOUSE_PASSWORD

And maybe CLICKHOUSE_PORT

May be related to https://forum.sentry.io/t/secure-clickhouse-connection-with-on-premise-snuba/14919
And https://github.com/getsentry/snuba/pull/2033

**Comment by enochtangg** [comment]
Hi @williamdes, thanks for raising this. We are looking to prioritizing this work.

**Comment by onewland** [comment]
@williamdes can you be more clear about what you need or what specifically isn't working for you? We already use these environment variables in the default settings (if you map all datasets to one cluster):

https://github.com/getsentry/snuba/blob/7a5bd19982deb86af5694ce98a38c878211cba14/snuba/settings/__init__.py#L91-L92

**Comment by williamdes** [comment]
Well, it seems like this was ignored. Maybe only by the rust workers?
I am not sure, but adding the envs in docker did not work and threw errors

**Comment by onewland** [comment]
ok, that makes sense

**Comment by xurui-c** [comment]
Hi William, do you mind telling me a little about how to reproduce the errors you saw? Was it running `sentry devservices up` and then `docker exec -it sentry_clickhouse clickhouse-client`

**Comment by xurui-c** [comment]
Hi @williamdes , could you provide the errors you saw? Thanks!

**Comment by williamdes** [comment]
I was running an external ClickHouse server and the errors are access denied auth errors in the CH server.
I have no logs for it now, but put a password 5o your default Clickhouse user and maybe create a new one too and start testing

**Comment by andrsp** [comment]
i'm using dedicated clickhouse with set up non-default user for sentry (called `sentry`)
seems like new rust-consumers reporting in log on start with right config credentials but tries to connect to clickhouse with user `default` (which is not allowed in my installation) and crashes with something like this:
```
{"timestamp":"...","level":"INFO","fields":{"message":"Starting Rust consumer","consumer_config.storages":"[StorageConfig { name: \"errors\", clickhouse_table_name: \"errors_dist\", clickhouse_cluster: ClickhouseConfig { host: \"clickhouse\", port: 9000, http_port: 8123, user: \"sentry\", password: \"redacted\", database: \"default\" }, message_processor: MessageProcessorConfig { python_class_name: \"ErrorsProcessor\", python_module: \"snuba.datasets.processors.errors_processor\" } }]"},"target":"rust_snuba::consumer"}
......
{"timestamp":"...","level":"ERROR","fields":{"error":"the strategy errored"},"target":"rust_snuba::consumer"}
```
clickhouse says:
```
 <Error> DynamicQueryHandler: Code: 516. DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name. (AUTHENTICATION_FAILED)
```
and i see no attempts to connect with defined user `sentry`
