### ISSUE TITLE
Unknown function 'notHandled'

### ISSUE THREAD

**Issue by caseyduquettesc** [getsentry/snuba#5783]
### Environment

Self hosted 24.3.0

### Steps to Reproduce

Saw this error in the clickhouse logs. I'm not sure what functionality triggered it, but looking at the Snuba code, it seems unexpected as `notHandled` should have been transformed into other syntax.

> `<Error> TCPHandler: Code: 46, e.displayText() = DB::Exception: Unknown function notHandled: While processing ((client_timestamp AS _snuba_timestamp) >= toDateTime('2024-03-17T14:56:52', 'Universal')) AND (_snuba_timestamp < toDateTime('2024-04-16T14:56:52', 'Universal')) AND ((project_id AS _snuba_project_id) IN tuple(218)) AND (notHandled() = 1) AND ((occurrence_type_id AS _snuba_occurrence_type_id) IN (4001, 4002, 4003)) AND (_snuba_project_id IN tuple(218)) AND ((group_id AS _snuba_group_id) IN (105510889, 116060410, 118366138, 118366139, 118366140, 118712775, 118712779))`

**Comment by volokluev** [comment]
Hi, thank you for the report, this is a bug (although not with snuba). It has been raised to the issues team

**Comment by serrrios** [comment]
+1

**Comment by rojinebrahimi** [comment]
+1

**Comment by onewland** [comment]
This should be fixed in the newest version, please let us know if it's still occurring and we can re-open

**Comment by kagodarog** [comment]
This still happens after upgrading from 24.6.0 to 24.8.0

**Comment by rh01** [comment]
how to resolve

**Comment by grindlife** [comment]
I am experiencing the same issue.   
Self hosted 24.8.0

**Comment by henri9813** [comment]
Hello, some news ?

**Comment by rommelfreddy** [comment]
hello @onewland , 
just updated to the latest version 25.1.0 for sentry, but do have the same issue.

**Comment by volokluev** [comment]
Hi all, this is not something that snuba can fix, sentry is querying the `search_issues` dataset with a custom function that is only implemented for errors. All snuba can do is reject it in a different way. I have reached out to the issues team again to try and get this fixed. 

FWIW I don't think this is something that actually affects the product functioning. Are folks seeing it show up in their product experience or just the logs?

**Comment by StirlingEngine** [comment]
@volokluev Logs only, as far as I can tell — but it's accompanied by a container restart, which isn't very pleasant.
