### ISSUE TITLE
snuba outcomes consumer lag growing unchecked

### ISSUE THREAD

**Issue by bkk-bcd** [getsentry/snuba#5796]
### Environment

`24.2.0`

### Steps to Reproduce

```
❯ ./kafka-consumer-groups.sh --group snuba-consumers --describe
Defaulted container "kafka" out of: kafka, kafka-init (init)

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-consumers events          0          818081          818089          8               rdkafka-9a908325-4c8a-45d9-bc52-afc12f787f20 /10.50.229.254  rdkafka
snuba-consumers outcomes        1          49642           69684           20042           rdkafka-d44d0320-f276-4185-9a0c-ec98b206b10b /10.50.216.20   rdkafka
snuba-consumers outcomes        0          6210800         6231145         20345           rdkafka-61835142-d985-450e-a852-2791e0c9cada /10.50.225.18   rdkafka
❯ ./kafka-consumer-groups.sh --group snuba-consumers --describe
Defaulted container "kafka" out of: kafka, kafka-init (init)

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-consumers events          0          819704          819708          4               rdkafka-9a908325-4c8a-45d9-bc52-afc12f787f20 /10.50.229.254  rdkafka
snuba-consumers outcomes        1          54331           78521           24190           rdkafka-d44d0320-f276-4185-9a0c-ec98b206b10b /10.50.216.20   rdkafka
snuba-consumers outcomes        0          6215366         6240019         24653           rdkafka-61835142-d985-450e-a852-2791e0c9cada /10.50.225.18   rdkafka
```

### Expected Result

I expect the consumers to be reading off the queue partitions and performing work. That doesn't appear to be happening.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by untitaker** [comment]
I haven't double-checked, but I see that current offset is growing at a different rate than lag. So I _think_ you have a consumer running, but it is too slow and you need more replicas (and potentially repartition the topic if you need more than two replicas)

outcomes isn't particularly critical for product usage, it is only relevant for "stats" page. If it's not worth the infra cost of adding more snuba-outcomes-consumers, you can also just let the lag grow

**Comment by bkk-bcd** [comment]
> I haven't double-checked, but I see that current offset is growing at a different rate than lag. So I _think_ you have a consumer running, but it is too slow and you need more replicas (and potentially repartition the topic if you need more than two replicas)
> 
> outcomes isn't particularly critical for product usage, it is only relevant for "stats" page. If it's not worth the infra cost of adding more snuba-outcomes-consumers, you can also just let the lag grow

Yup that was exactly it. I added partitions and replicas. However, ignoring this means a lot of growth in Kafka unless you tune correctly. Anyways, I was good with just scaling it out a bit its not enough cost to be noticeable for us and we do use that stats page to some degree.

Thanks!
