### ISSUE TITLE
Monitor the size of the unbounded channel that consumer stream clickhouse writes to

### ISSUE THREAD

**Issue by john-z-yang** [getsentry/snuba#5874]
Occasionally seeing very high memory usage in certain snuba consumers (counters and gauges observed so far). Seems to be correlated with connectivity issues.

The leading theory is we're using an [unbounded_channel](https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.unbounded_channel.html) from tokio between the arroyo strategy that creates the http batch and the http client. When the http client experience connection problems, the channel size increase leading to high memory.

Add metrics to the size of the unbounded channel to tell us if this is indeed the case.

**Comment by MeredithAnya** [comment]
Adding that we also saw high mem usage for spans as well starting today
