### ISSUE TITLE
Deploy victoria metrics in sandbox environment

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#5943]
```[tasklist]
### Tasks
- [x] If necessary, add load balancers in front of vm-select and vm-insert nodes
```

**Comment by ayirr7** [comment]
https://github.com/getsentry/tsdb-evaluation-sandbox/pull/17

for installation and running the processes for each component

**Comment by enochtangg** [comment]
https://github.com/getsentry/tsdb-evaluation-sandbox/pull/31

Load balancers not strictly necessary for cluster mode. PR contains scripts for testing connectivity.
