### ISSUE TITLE
Figure out if vector can be used to write metrics to clickhouse

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#5945]
The goal of this task is to find out if we can use vector to read messages from either kafka/pub-sub and then write metrics data to clickhouse. This is the clickhouse sink which is being referred to https://vector.dev/docs/reference/configuration/sinks/clickhouse/.

In order to test, you can use the sample data which is captured in https://github.com/getsentry/tsdb-evaluation-sandbox/blob/main/vector/source/example_output.json and use either the [stdin](https://vector.dev/docs/reference/configuration/sources/stdin/) source or the [file](https://vector.dev/docs/reference/configuration/sources/file/) source. Those source say that they are specifically for logs so not sure if they would work. But lets try and see.

Once we find the answer to this, there are a few things which will need to happen:
### Vector works
Nice. Save the example which works under https://github.com/getsentry/tsdb-evaluation-sandbox/tree/main/vector under a directory called `sandbox`.
Then we need to build the k8s yaml file which we can use to deploy vector in the sandbox environment. This effort would be similar to the yaml file task listed in https://github.com/getsentry/snuba/issues/5938 

### Vector does not work
In that case we should write a snuba rust consumer which can read messages from kafka and perform the necessary transformation to write data to clickhouse.
Once the consumer is written we will need to write the k8s yaml file to deploy the rust consumer in sandbox environment.

**Comment by untitaker** [comment]
https://github.com/getsentry/tsdb-evaluation-sandbox/pull/9
