### ISSUE TITLE
Widgets in the Dashboards are throwing 504

### ISSUE THREAD

**Issue by sree-warrier** [getsentry/snuba#5962]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

nil

### Docker Compose Version

nil

### Steps to Reproduce

We have created few telemetry dashboards with different types of widgets. While checking the data with longer timestamp (20 or 30 days) most of the widgets throw 504. Exact error is like this 

`GET /organizations/{orgSlug}/events/ 504`

Attaching the screen-shot too. 

What could be the reason for this, i can find proper doc on the widget get call from which database. We tried to changes the timeout configs of clickhous, but it didnt works.  Have increased the resources for postgres and clickhouse too, still issues were seen. Let us know how we can track this.

<img width="825" alt="Screenshot 2024-05-15 at 11 17 41 AM" src="https://github.com/getsentry/self-hosted/assets/52820728/45ce2db6-f039-4c4c-a0ee-d9fd50d00cd3">

### Expected Result

All widget in dashboards should load without any issue for atleast 30days of time frame.

### Actual Result

nil

### Event ID

nil

**Comment by xurui-c** [comment]
Could you provide a link to the dashboard? It seems like your queries are missing a project/organization id, which could be causing the connection error

**Comment by mcannizz** [comment]
@xurui-c should allocation policy violations be occurring in self-hosted? This looks like a bug to me.

**Comment by sree-warrier** [comment]
@xurui-c its a selfhosted sentry. Also seeing this issue regularly now. Seems some config changes need to be done with snuba. Let us know if any such configuration been referred

**Comment by nikhars** [comment]
Hi. The snuba config which disables the allocation policy on self hosted can be found [here](https://github.com/getsentry/snuba/blob/master/snuba/settings/settings_self_hosted.py#L6). You can see that the allocation policy is marked as `False` there. Hence it shouldn't be active.

1. Can you validate what value you are seeing in the configuration file of your environment? Is that value set to `True` or `False`?
2. Do you have a mechanism where you override certain values in your environment? If so, can you turn the option to `False` and see if you still see the issue?
