### ISSUE TITLE
Best compression strategy to store tag keys and tag values

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#6002]
Tag values are one of the largest columns on the metrics clusters today. When we get rid of indexing, tag keys would also add to the total size of the column on the cluster. We should figure out how we want to store tag keys and tag values. Since both are an array of strings, the focus should be on finding out the best way store an array of strings.
```sql
some_string Array(Strings)
```

Refer to this document for details on column compressions https://clickhouse.com/docs/en/sql-reference/statements/create/table#general-purpose-codecs

Some things to note:
- In the metrics table, the ordering key will always have the metric name before tag keys. And in theory, the tag keys should most often be the same for a given metric. Hence consecutive rows of the table should inherently have the same set of tag keys.
- The tag values do not have the same characteristics as the tag keys columns. But tag values also, by nature have similar values across different rows. That means a good compression strategy could be useful for them as well.

**Comment by john-z-yang** [comment]
Data is now flowing from vector to clickhouse

```sql

   ┌─table──────────────────────────────────────┬─column─────┬─compressed─┬─uncompressed─┬─compr_ratio─┬──rows_cnt─┬─avg_row_size─┐
1. │ generic_metric_counters_raw_local_baseline │ tags.key   │ 551.92 MiB │ 13.55 GiB    │       25.14 │ 179983153 │        80.83 │
2. │ generic_metric_counters_raw_local_zstd_1   │ tags.key   │ 228.96 MiB │ 13.55 GiB    │       60.62 │ 179983153 │        80.86 │
3. │ generic_metric_counters_raw_local_zstd_2   │ tags.key   │ 228.55 MiB │ 13.55 GiB    │       60.72 │ 179983504 │        80.85 │
4. │ generic_metric_counters_raw_local_baseline │ tags.value │ 2.25 GiB   │ 12.21 GiB    │        5.42 │ 179983153 │        72.83 │
5. │ generic_metric_counters_raw_local_zstd_1   │ tags.value │ 980.93 MiB │ 12.21 GiB    │       12.75 │ 179983153 │        72.86 │
6. │ generic_metric_counters_raw_local_zstd_2   │ tags.value │ 936.81 MiB │ 12.21 GiB    │       13.35 │ 179983504 │        72.85 │
   └────────────────────────────────────────────┴────────────┴────────────┴──────────────┴─────────────┴───────────┴──────────────┘

```

Will be designing queries next to measure query performance differences

**Comment by john-z-yang** [comment]
Done, it seems like Zstd(2) is the best in the group. See the notion doc in Generic Metrics Platform notion page for more details.
