### ISSUE TITLE
Best compression strategy to store all raw values

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#6003]
We want to be able to run an experiment where for distributions, we want to see if storing the raw values rather than the aggregated values has more benefits. In a scenario where we store the raw values, all values would be stored as an array of floats
```sql
values Array(Float64)
```

If we store all values, the values column will inherently become very large. In a scenario like that, what compression strategy should be used to save on disk space?

Some notes:
- A general observation we can make is that timeseries data points don't deviate too often from a baseline value. In a scenario like that, does [gorilla](https://clickhouse.com/docs/en/sql-reference/statements/create/table#gorilla) codec help us?

**Comment by john-z-yang** [comment]
Was stuck on deserializing distribution values in vector.
This is now solved:
https://github.com/getsentry/tsdb-evaluation-sandbox/commit/8aa08e05f89c5fa842aebd2c164ec7ecb481e006
Working on creating the tables now

**Comment by john-z-yang** [comment]
Done, it seems like Delta + Zstd(1) is the best in the group. See the notion doc in Generic Metrics Platform notion page for more details.
