### ISSUE TITLE
Does Snuba deduplicate data before sending into Clickhouse?

### ISSUE THREAD

**Issue by chipzzz** [getsentry/snuba#6010]
I'm wondering how duplicate data is handled when we  have all Snuba consumers set to "earliest" and say there's an outage thus upon recovery snuba consumers would read from the earliest offset of the topic since we have it set to earliest, thus re-consuming previously consumed events before the outage.

In that scenario, at which point does deduplication happen if at all ? Does Snuba deduplicate already ingested data ? Does Clickhouse?

Based on Snuba docs this what I see, is this related to what i'm talking about?

```
Data ingestion is most effective in batches (both for Kafka but especially for Clickhouse). Our consumers support batching and guarantee that one batch of events taken from Kafka is passed to Clickhouse at least once. By properly selecting the Clickhouse table engine to deduplicate rows we can achieve exactly once semantics if we accept eventual consistency.
```

**Comment by volokluev** [comment]
Snuba consumers do not deduplicate data. If the primary key for two rows is the same, clickhouse will merge them together when it issues a merge.
