### ISSUE TITLE
rust-consumer does not receive signals

### ISSUE THREAD

**Issue by doc-sheet** [getsentry/snuba#6031]
### Environment

snuba 24.5.1 from https://github.com/getsentry/self-hosted

### Steps to Reproduce

1. run some rust-consumer, for example
```
snuba rust-consumer --storage spans --consumer-group snuba-spans-consumers --auto-offset-reset=latest --max-batch-time-ms 1000 --no-strict-offset-reset
```
2. send SIGTERM to main process with `kill -s SIGTERM <pid>` or just do `docker stop snuba-spans-consumer`
3. check exit code / docker events

### Expected Result

Consumer gracefully stops

### Actual Result

Container killed by sigkill

Looks like master process does not propagate signals to rust consumer.
For example python version has [some handlers](https://github.com/getsentry/snuba/blob/38a902ed765497a7d55398bf2cad274c07703c78/snuba/cli/consumer.py#L277) for it.

**Comment by untitaker** [comment]
The handler for Rust is here: https://github.com/getsentry/snuba/blob/869e1a7a063581ee5284bab315498630bff106df/rust_snuba/src/consumer.rs#L242

it seems it may only handle SIGINT and not SIGTERM, but it's not clear.

Patches welcome
