### ISSUE TITLE
Better error messaging for unresolved metrics errors

### ISSUE THREAD

**Issue by evanh** [getsentry/snuba#6084]
When a column isn't resolved properly, the query returns an ambiguous error message.

`validation failed for entity generic_metrics_distributions: Entity generic_metrics_distributions: Query column 'wrapper_type' does not exist`

This should return a more obvious "tag key not resolved error" or something along those lines.

**Comment by onkar** [comment]
@vgrozdanic the error is coming from here: https://github.com/getsentry/snuba/blob/d4b164c06710e15bed33d868102305adf8fe495c/snuba/query/validation/validators.py#L186 Do you have any preference on the error message text? I am not following the `"tag key not resolved error"` message in the issue description and would appreciate some help in wording. Thanks.
