### ISSUE TITLE
snuba.clickhouse.errors.ClickhouseError: DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name

### ISSUE THREAD

**Issue by chipzzz** [getsentry/snuba#6174]
@MeredithAnya  @john-z-yang 

From https://github.com/getsentry/snuba/pull/5857

>so this is just affecting self-hosted folks (who should be able to upgrade soon) but yeah - I guess if we had had 21.8 test suite for https://github.com/getsentry/snuba/pull/5818 we might have caught it oh we did, that's the default, but self-hosted uses 21.6

Yes this is definitely impacting us, which version of Clickhouse should we be using since Snuba has compatibility issues.
```
Snuba has only been tested on Clickhouse versions up to 23.3.8.22
```

I'm using Clickhouse version 23.4.1 and seeing the following, making me reluctant to upgrade further.

```
snuba.clickhouse.errors.ClickhouseError: DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
```

with the following config
 ```
          externalClickhouse: {
            existingSecret: 'sentry-clickhouse',
            existingSecretKey: 'password',
            singleNode: false,
            clusterName: 'default',
            host: 'clickhouse',
            tcpPort: 9000,
            httpPort: 8123,
            username: 'default',
            password: ''
            database: 'default'
          },
    ```

**Comment by MeredithAnya** [comment]
hi @chipzzz 

>Currently using 3.5.0 which is just above Clickhouse version 23.3.8.22. I've seen problems with snuba and consumers going past that with latest Cliickhouse version as per the compatibility warnings.

iirc you should be able to upgrade to CH 23.8.11.19 which should be the [base version](https://github.com/getsentry/self-hosted/blob/053f4010b61adf4677d8ac81488d41dd95461fba/docker-compose.yml#L204) now and the [install script](https://github.com/getsentry/self-hosted/blob/053f4010b61adf4677d8ac81488d41dd95461fba/install/upgrade-clickhouse.sh#L20) should handle that upgrade

So hopefully upgrading the clickhouse helm chart will solve things for you, although if the helm chart version `3.6.9` uses a higher clickhouse version than `23.8.11.19`. If that is the case we can reopen that PR cc @john-z-yang
