### ISSUE TITLE
Add support for setting http_batch_join_timeout via environment variables

### ISSUE THREAD

**Issue by gurgenyegor** [getsentry/snuba#6306]
Currently, the http_batch_join_timeout value in Snuba is configured through a configuration file or defaults, with no option to set it via environment variables. To enhance flexibility and allow for easier configuration, especially in containerized environments, I propose adding support for setting the http_batch_join_timeout value using an environment variable.

This would allow users to dynamically adjust the timeout based on their environment without modifying configuration files, making it easier to manage deployments across different environments.
Proposed Solution:

Introduce a new environment variable, such as `SNUBA_HTTP_BATCH_JOIN_TIMEOUT`, which will override the default `http_batch_join_timeout` value when present.
Ensure backward compatibility by maintaining the current configuration method if the environment variable is not set.

This feature would simplify configuration management in scenarios like Docker or Kubernetes deployments, where environment variables are commonly used.

code:
```
        batch_join_timeout = state.get_config("http_batch_join_timeout", 60)
        # IMPORTANT: Please read the docstring of this method if you ever decide to remove the
        # timeout argument from the join method.
        batch.join(timeout=batch_join_timeout)
```

**Comment by mcannizz** [comment]
@untitaker is there an analogous setting in the Rust consumers?

**Comment by untitaker** [comment]
this is called batch_write_timeout in the rust consumer. I suggest to unify those settings, and expose them via `settings/__init__.py`. In that file, we may read from envvars as well. I definitely do not recommend reading the envvar directly from rust consumers, as it causes too much fragmentation with regard to how configuration is resolved.

**Comment by gurgenyegor** [comment]
@davidtsuk thanks for your quick solution!!!!
