### ISSUE TITLE
How to enable sasl with rust_consumer?

### ISSUE THREAD

**Issue by max107** [getsentry/snuba#6358]
### Environment

docker, self-hosted

### Steps to Reproduce

1. just
2. enable
3. sasl with external kafka

### Expected Result

no error

### Actual Result

```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: KafkaError (Client creation error: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN)
```

version 24.9.0

**Comment by max107** [comment]
easiest solution - rebuild docker image

```
ENV CARGO_FEATURE_SSL=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on
```

**Comment by untitaker** [comment]
We don't support this usecase, but if you want to contribute a patch to make rdkafka build with SSL, feel free to. IIRC the last SASL patch was also made by an external contributor.
