### ISSUE TITLE
Improve docker tag names

### ISSUE THREAD

**Issue by daniilr** [getsentry/snuba#715]
It seems that old builds listed here:

https://hub.docker.com/r/getsentry/snuba/builds

are not available for pull 

```
root@baops05:/opt/onpremise# docker pull getsentry/snuba:ab0ca24f2aa1058fcf6df036617f765a23275d86
Error response from daemon: manifest for getsentry/snuba:ab0ca24f2aa1058fcf6df036617f765a23275d86 not found

```

Because all images are tagged just like "latest".
And currently there is no way to pull working image 

Can you please remove corrupted image and tag previous working as latest?
Would also be good to keep possibility to pull by commit hashtags for easier rollbacks in case something breaks

**Comment by BYK** [comment]
This is already done via #700 and #711.

**Comment by daniilr** [comment]
I was actually suggesting opposite thing – to keep ability to rollback to the previous image. Current image in docker hub[ is broken](https://github.com/getsentry/snuba/commit/ea2d584aedf16e1418970322f756c06ee89e4dd8#diff-c5e6ef18a6af4877b10c332606c4d9d1R435) and there is no way to quickly rollback (I had to build image manually). Not sure if this is the best solution though, I think normally such image shouldn't build and be published because it's not that hard to catch such exception.

**Comment by BYK** [comment]
@daniilr we have pushed a fixed version of the image and you should be able to use the git commit SHAs as tags for rollback. We have also started work to prevent this from happening again and added some immediate measures to cut the risk substantially.
