### ISSUE TITLE
Unknown field found while parsing JSONEachRow format

### ISSUE THREAD

**Issue by iAziz786** [getsentry/snuba#760]
I'm getting the above error while I'm receiving an error event. Currently, I'm using a self-hosted docker of Sentry. I have also asked about it in the [forum](https://forum.sentry.io/t/unknown-field-found-while-parsing-jsoneachrow/8755), but haven't received any response regarding this.  Here is the stack trace of the error.

```
snuba-consumer_1          | 2020-02-07 02:22:33,189 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 450}
snuba-consumer_1          | 2020-02-07 02:22:40,701 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=450, hi=450)}): forced:False size:False time:True
snuba-consumer_1          | Traceback (most recent call last):
snuba-consumer_1          |   File "/usr/local/bin/snuba", line 11, in <module>
snuba-consumer_1          |     load_entry_point('snuba', 'console_scripts', 'snuba')()
snuba-consumer_1          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
snuba-consumer_1          |     return self.main(*args, **kwargs)
snuba-consumer_1          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
snuba-consumer_1          |     rv = self.invoke(ctx)
snuba-consumer_1          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
snuba-consumer_1          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
snuba-consumer_1          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
snuba-consumer_1          |     return ctx.invoke(self.callback, **ctx.params)
snuba-consumer_1          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
snuba-consumer_1          |     return callback(*args, **kwargs)
snuba-consumer_1          |   File "/usr/src/snuba/snuba/cli/consumer.py", line 156, in consumer
snuba-consumer_1          |     consumer.run()
snuba-consumer_1          |   File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
snuba-consumer_1          |     self._run_once()
snuba-consumer_1          |   File "/usr/src/snuba/snuba/utils/streams/batching.py", line 142, in _run_once
snuba-consumer_1          |     self._flush()
snuba-consumer_1          |   File "/usr/src/snuba/snuba/utils/streams/batching.py", line 233, in _flush
snuba-consumer_1          |     self.worker.flush_batch(self.__batch_results)
snuba-consumer_1          |   File "/usr/src/snuba/snuba/consumer.py", line 98, in flush_batch
snuba-consumer_1          |     self.__writer.write(inserts)
snuba-consumer_1          |   File "/usr/src/snuba/snuba/clickhouse/http.py", line 95, in write
snuba-consumer_1          |     raise ClickHouseError(int(code), type, message)
snuba-consumer_1          | snuba.clickhouse.http.ClickHouseError: [117] DB::Exception: Unknown field found while parsing JSONEachRow format: _tags_flattened: (at row 1)
snuba-consumer_1          | + '[' consumer = bash ']'
snuba-consumer_1          | + '[' c = - ']'
snuba-consumer_1          | + '[' consumer = api ']'
snuba-consumer_1          | + snuba consumer --help
snuba-consumer_1          | + set -- snuba consumer --auto-offset-reset=latest --max-batch-time-ms 750
snuba-consumer_1          | + exec gosu snuba snuba consumer --auto-offset-reset=latest --max-batch-time-ms 750
snuba-consumer_1          | 2020-02-07 02:22:50,589 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 451}
```

I would love the help to find and fix this issue.

**Comment by fpacifici** [comment]
Hi,

the issue we observe there is that there is a change in the Snuba schema that has not yet been applied to your Clickhouse schema (the _tags_flattened column). It happened here: https://github.com/getsentry/snuba/pull/703

In most cases starting Snuba will trigger the migration script but that depends on how you are running Snuba.
So in order to run the script manually and if you installed Sentry via docker with the onpremise instructions  (https://github.com/getsentry/onpremise) this should do the trick

`docker run -it YOUR_SNUBA_IMAGE_ID migrate`

Should it not work, could you please attach the logs of the docker command and confirm whether you are running sentry through the onpremise docker procedure explained above ?

**Comment by iAziz786** [comment]
Yes, I'm running Sentry through getsentry/onpremise docker. Here are the commands that I ran.

`docker images` and copied the container ID of `getsentry/snuba:latest`.

After that I ran `docker run -it <<snuba_id>> migrate` by which I got this error.

**Error Logs**
```
+ '[' migrate = bash ']'
+ '[' m = - ']'
+ '[' migrate = api ']'
+ snuba migrate --help
+ set -- snuba migrate
+ exec gosu snuba snuba migrate
2020-02-07 11:47:45,419 Migrating dataset groupedmessage
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 226, in connect
    self.socket = self._create_socket()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 213, in _create_socket
    raise err
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 204, in _create_socket
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrate.py", line 41, in migrate
    run(clickhouse, dataset)
  File "/usr/src/snuba/snuba/migrate.py", line 51, in run
    _run_schema(conn, schema)
  File "/usr/src/snuba/snuba/migrate.py", line 26, in _run_schema
    local_schema = get_schema()
  File "/usr/src/snuba/snuba/migrate.py", line 22, in get_schema
    for cols in conn.execute("DESCRIBE TABLE %s" % clickhouse_table)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 196, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 171, in force_connect
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 251, in connect
    '{} ({})'.format(e.strerror, self.get_description())
clickhouse_driver.errors.NetworkError: Code: 210. Cannot assign requested address (localhost:9000)
```

@fpacifici let me know if you need any other details.

**Comment by fpacifici** [comment]
Sorry I forgot a piece, when you run that you need to ensure the Snuba container can access the same network clickhouse is listening on when you run the script.
This depends on how your network is configured.

`docker run --env CLICKHOUSE_HOST=THE_HOST_RUNNING_CLICKHOUSE --network=NETWORK_SENTRY_IS_RUNNING_ONTO -it YOUR_SNUBA_IMAGE migrate`

Assuming 
THE_HOST_RUNNING_CLICKHOUSE = "clickhouse" as in the default onpremise settings
NETWORK_SENTRY_IS_RUNNING_ONTO should be "sentry_onpremise_default" by default, but you can find the actual name with `docker network ls`

Should that still not work, this should work no matter what for this specific script
`docker run --env CLICKHOUSE_HOST=localhost --network='container:YOUR_CLICKHOUSE_CONTAINER_NAME' -it YOUR_SNUBA_IMAGE_ID migrate`

**Comment by iAziz786** [comment]
This solves the issue I have started receiving the events.

Thanks, @fpacifici for your valuable support.

**Comment by BYK** [comment]
Btw re-running the install script on the onpremise repo or running `docker-compose run --rm snuba-api migrate` would have been an easier and safer solution rather than running direct `docker run` commands on `compose` managed containers/images.

**Comment by iAziz786** [comment]
Okay, I'll remember this for the next time if me or anyone face the similar issue.

Thanks @BYK

**Comment by golimer** [comment]
getsentry/snuba 0846d6f9cd34c5a6c52b695d3713cd31897514cd
/srv/docker-compose# docker-compose run --rm snuba-api migrate
Creating docker-compose_snuba-api_run ... done
+ '[' m = - ']'
+ snuba migrate --help
+ exec migrate
./docker_entrypoint.sh: line 16: exec: migrate: not found

ERROR:
/snuba-consumer","source":"stderr","log":"snuba.clickhouse.errors.ClickhouseWriterError: [117] Unknown field found while parsing JSONEachRow format: message_timestamp: (at row 1)

any ideas?

**Comment by BYK** [comment]
@golimer the correct command is `docker-compose run --rm snuba-api migrations migrate --force`

I strongly advice you to follow the on-premise repo and the install script there or at least check there before posting under issues here.
