### ISSUE TITLE
Add possibility to prefix snuba kafka topics

### ISSUE THREAD

**Issue by hisabimbola** [getsentry/snuba#838]
I have a on prem deployment and the kafka deployment we have is not only used by sentry. Currently the topics are generic like "event". Not possible to really tell that the topic belongs to sentry. It would be nice to have an option to pass a prefix value and all sentry topics will be prefix by that value

_I am not sure if this is the right place to open this issue or in the main sentry repo but since I think it's very specific to snuba. I opened here and can reopen in sentry repo if @BYK thinks otherwise_

**Comment by BYK** [comment]
@hisabimbola thanks a lot for using Sentry and asking about this. Although I definitely see the use case, I am not sure if it makes sense to implement and maintain this on our side. I'll let @tkaemming and @fpacifici to make the final decision and I'm happy to support this over at getsentry/onpremise if it ever gets implemented.

**Comment by fpacifici** [comment]
Hi,
while there is no way to generally prefix Kafka topic names over all Sentry, there are ways to set them up manually through config.

Also there is no officially documented and supported way to set topics name as of now, though I can explain how to do it if you need it. Unfortunately we cannot guarantee backward compatibility or support on this setup though. Use it at your own risk.

You can override these parameters in sentry  (you can use your preferred way to override those parameters as explained in the Configuration section of Sentry doc)
https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L1687-L1692 .

That should be enough to make sentry produce and consume on the topic you like.

On the Snuba side things are a little less mature. Who really cares about the topics are the Snuba consumers, and all consumers have a CLI argument to set the consumer 
https://github.com/getsentry/snuba/blob/master/snuba/cli/consumer.py#L15-L18
The way to change it depends on how you are running the consumer (docker compose, devservers, from source, etc.)
Also you will have to manually create the topic because the snuba bootstrap process will keep creating the event topic.

**Comment by chadwhitacre** [comment]
@fpacifici What do you think, should we close this issue? It seems we're not going to support this, the tips you provided are enough to get people pointed in the right direction it seems (from https://github.com/getsentry/sentry/issues/31721#issuecomment-1037208376).

**Comment by lynnagara** [comment]
Closing since this is supported via settings overrides. Though the override will need to defined for every topic, you cannot just set a prefix in one place.

**Comment by nttdocomo** [comment]
@hisabimbola @chadwhitacre @fpacifici @lynnagara @BYK After two years of intermittent research, I've validated the feasibility of custom topics and implemented them in my own project. So far, it seems to be running smoothly. Let me briefly explain the entire customization process.

> [!CAUTION]
> It's all base on 21.5.0

# Which services need custom topics
- relay
- sentry
- snuba
## Relay
[docs](https://getsentry.github.io/relay/relay_config/struct.Processing.html)
processing has a topics config
[source](https://github.com/getsentry/relay/blob/21.5.0/relay-config/src/config.rs#L675-L686)
From the source code we can see relay use 6 topics. So we need to add topics in config.yml
```yaml
processing:
  topics:
    events: "sentry-dev-ingest-events"
    attachments: "sentry-dev-ingest-attachments"
    transactions: "sentry-dev-ingest-transactions"
    outcomes: "sentry-dev-outcomes"
    sessions: "sentry-dev-ingest-sessions"
    metrics: "sentry-dev-ingest-metrics"
```
## Sentry
Sentry have two parts
### sentry.conf.py
```python
KAFKA_EVENTS = "sentry-dev-events"
KAFKA_OUTCOMES = "sentry-dev-outcomes"
KAFKA_EVENTS_SUBSCRIPTIONS_RESULTS = "sentry-dev-events-subscription-results"
KAFKA_TRANSACTIONS_SUBSCRIPTIONS_RESULTS = "sentry-dev-transactions-subscription-results"
KAFKA_SUBSCRIPTION_RESULT_TOPICS = {
    "events": KAFKA_EVENTS_SUBSCRIPTIONS_RESULTS,
    "transactions": KAFKA_TRANSACTIONS_SUBSCRIPTIONS_RESULTS,
}
# KAFKA_INGEST_EVENTS = "ingest-events"
KAFKA_INGEST_EVENTS = "sentry-dev-ingest-events"
KAFKA_INGEST_ATTACHMENTS = "sentry-dev-ingest-attachments"
KAFKA_INGEST_TRANSACTIONS = "sentry-dev-ingest-transactions"

KAFKA_TOPICS = {
    KAFKA_EVENTS: {"cluster": "default", "topic": KAFKA_EVENTS},
    KAFKA_OUTCOMES: {"cluster": "default", "topic": KAFKA_OUTCOMES},
    KAFKA_EVENTS_SUBSCRIPTIONS_RESULTS: {
        "cluster": "default",
        "topic": KAFKA_EVENTS_SUBSCRIPTIONS_RESULTS,
    },
    KAFKA_TRANSACTIONS_SUBSCRIPTIONS_RESULTS: {
        "cluster": "default",
        "topic": KAFKA_TRANSACTIONS_SUBSCRIPTIONS_RESULTS,
    },
    # Topic for receiving simple events (error events without attachments) from Relay
    KAFKA_INGEST_EVENTS: {"cluster": "default", "topic": KAFKA_INGEST_EVENTS},
    # Topic for receiving 'complex' events (error events with attachments) from Relay
    KAFKA_INGEST_ATTACHMENTS: {"cluster": "default", "topic": KAFKA_INGEST_ATTACHMENTS},
    # Topic for receiving transaction events (APM events) from Relay
    KAFKA_INGEST_TRANSACTIONS: {"cluster": "default", "topic": KAFKA_INGEST_TRANSACTIONS},
}
``` 
### runner
```shell
run query-subscription-consumer --commit-batch-size 1 --topic sentry-events-subscription-results
run query-subscription-consumer --commit-batch-size 1 --topic sentry-dev-transactions-subscription-results
run post-process-forwarder --commit-batch-size 1 --commit-log-topic sentry-dev-snuba-commit-log
```
## Snuba
### setting.xxx.py
[source](https://github.com/getsentry/snuba/blob/21.5.0/snuba/utils/streams/topics.py)
snuba use KAFKA_TOPIC_MAP to map the topics, so we just need to modify the KAFKA_TOPIC_MAP in out setting file
```python
KAFKA_TOPIC_MAP = {
  "events": "sentry-dev-events",
  "event-replacements": "sentry-dev-event-replacements",
  "event-replacements-legacy": "sentry-dev-event-replacements-legacy",
  "snuba-commit-log": "sentry-dev-snuba-commit-log",
  "cdc": "sentry-dev-cdc",
  "outcomes": "sentry-dev-outcomes",
  "ingest-sessions": "sentry-dev-ingest-sessions",
  "events-subscription-results": "sentry-dev-events-subscription-results",
  "transactions-subscription-results": "sentry-dev-transactions-subscription-results",
  "snuba-queries": "sentry-dev-snuba-queries",
}
```
or you can do this
```python
from snuba.utils.streams.topics import Topic

KAFKA_TOPIC_MAP = {}

KAFKA_TOPIC_PREFIX = 'sentry-dev-'

for topic in Topic:
    KAFKA_TOPIC_MAP[topic.value] = '%s%s' % (KAFKA_TOPIC_PREFIX,topic.value)
```
### runner
- --commit-log-topic vakue in snuba-transactions-subscriptions-consumers，snuba-events-subscriptions-consumers，transactions_group
- --topic value in snuba-transactions-subscriptions-consumers，snuba-events-subscriptions-consumers
```shell
consumer --storage transactions --consumer-group transactions_group --auto-offset-reset=latest --max-batch-time-ms 750 --commit-log-topic=sentry-dev-snuba-commit-log
subscriptions --auto-offset-reset=latest --consumer-group=snuba-events-subscriptions-consumers --topic=sentry-dev-events --result-topic=events-subscription-results --dataset=events --commit-log-topic=sentry-dev-snuba-commit-log --commit-log-group=snuba-consumers --delay-seconds=60 --schedule-ttl=60 --partitions=3
subscriptions --auto-offset-reset=latest --consumer-group=snuba-transactions-subscriptions-consumers --topic=sentry-dev-events --result-topic=events-subscription-results --dataset=events --commit-log-topic=sentry-dev-snuba-commit-log --commit-log-group=snuba-consumers --delay-seconds=60 --schedule-ttl=60 --partitions=3
```
That's all. Enjoy it.

**Comment by chadwhitacre** [comment]
Wow. Thanks for sticking with it and reporting back, @nttdocomo! Also, thanks for teaching me about [Markdown alerts](https://github.com/orgs/community/discussions/16925). :]
