### ISSUE TITLE
The environment variable DATASET_MODE does not work

### ISSUE THREAD

**Issue by jiankunking** [getsentry/snuba#847]
We deployed sentry ourselves, where clickhous builds clusters, so we wanted snuba to create distributed tables when it created tables.I specified DATASET_MODE to be dist and distributed, but the created table is still the local table.

table name                    |
------------------------|
errors_local            |
groupassignee_local     |
groupedmessage_local    |
outcomes_hourly_local   |
outcomes_mv_hourly_local|
outcomes_raw_local      |
sentry_local            |
sessions_hourly_local   |
sessions_hourly_mv_local|
sessions_raw_local      |
transactions_local      |

I also changed settings.py to take DATASET_MODE from the environment variable.
[https://github.com/getsentry/snuba/blob/master/snuba/settings.py#L15](https://github.com/getsentry/snuba/blob/master/snuba/settings.py#L15)

**Comment by fpacifici** [comment]
Hi, sorry for the delay.
Distributed tables are not officially supported. DATASET_MODE would switch to distributed table, but bootstrap won't work. You would have to manage your tables (create and all DDL operations) manually. This is not a support process, I can give you some hints, but you would be doing it at your own risk.

On the other hand, we are working on this support though we cannot commit to a timeline at this time.

**Comment by jiankunking** [comment]
Sentry has taught me.
There is no such thing as a free lunch.

**Comment by envestcc** [comment]
Hi, i also want to deploy sentry in production. 
Is there any progress about clickhouse with distributed tables ?
