### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by azmeuk** [getsentry/snuba#868]
Hi.
I could not find snuba on pypi, and I could not find documentation on snuba packaging either.
Is there any plan to release snuba on Pypi?

**Comment by chadwhitacre** [comment]
Why is this helpful?

**Comment by chadwhitacre** [comment]
[Hrm](https://github.com/getsentry/self-hosted/issues/1654). 🐭

**Comment by azmeuk** [comment]
Same here. The infrastructure in my company is well suited for deploying pypi packages, not so much for docker images at the moment.

**Comment by mcannizz** [comment]
While I understand that pypi packaging could be helpful for some folks, we don't plan to distribute Snuba in this way.
