### ISSUE TITLE
snuba doesn't fully log Kafka/Confluent connectivity issues.

### ISSUE THREAD

**Issue by drook** [getsentry/snuba#964]
Right now snuba doesn't fully log Kafka/Confluent connectivity issues.

For instance when Snuba is able to connect to kafka and retrieve events this looks like this:
````
May 25 02:32:50 dev syslogd: last message repeated 7 times
May 25 02:33:07 dev snuba[53439]: 2020-05-25 02:33:07,431 Flushing 1 items (from {Partition(topic=Topic(name='events'), index=0): Offsets(lo=1170, hi=1170)}): forced:False size:False time:True
May 25 02:33:08 dev snuba[53439]: 2020-05-25 02:33:08,347 Worker flush took 915ms
May 25 02:33:10 dev snuba[53445]: 2020-05-25 02:33:10,385 Flushing 1 items (from {Partition(topic=Topic(name='event-replacements'), index=0): Offsets(lo=1, hi=1)}): forced:False size:False time:True
May 25 02:33:10 dev snuba[53445]: 2020-05-25 02:33:10,518 Replacing 1268 rows took 76ms
May 25 02:33:10 dev snuba[53445]: 2020-05-25 02:33:10,518 Worker flush took 132ms
````

But when, for example, Kafka hostname cannot be resolved, and upon connection it's returned in further connect descriptor, Snuba is silent about this fact. It can only be determined using strace/truss/ktrace/systemtap/dtrace frameworks.

**Comment by lynnagara** [comment]
Passing `--log-level=debug` or `--log-level=info` outputs the connection errors
