### ISSUE TITLE
Add support for replicated tables to bootstrap

### ISSUE THREAD

**Issue by chhetripradeep** [getsentry/snuba#970]
In production clickhouse setup, generally it's recommend to use replicated tables for mergetree family for high availability. Right now, there is no way to create replicated table via snuba bootstrap.

**Comment by fpacifici** [comment]
Hi, thanks for reaching out. 
This is a very good question. Indeed there is no way yet (unless you create your own distributed tables, set up DATASET_MODE to `dist` in settings and manage schema migrations manually. This is not a supported process, do it at your own risk).

We are working on supporting this, though we cannot commit to a timeline at this time.

**Comment by chhetripradeep** [comment]
Hello @fpacifici thank you for the response. I tried using Replicated tables in our setup and it seems to work well, though i am not sure about how to sentry cleanup task will work. I still have to test that part. Otherwise everything looks good.

**Comment by lynnagara** [comment]
Closing since this was done. The drop partition statements created by cleanup get replicated so technically you can just point the script at one of the replicas.
